// Generated by rstantools.  Do not edit by hand.

/*
    blouch is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    blouch is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with blouch.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.37.0-rc3
#include <stan/model/model_header.hpp>
namespace model_blouchOU_direct_postpc_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 85> locations_array__ =
  {" (found before start of program)",
  " (in 'blouchOU_direct_postpc', line 28, column 2 to column 22)",
  " (in 'blouchOU_direct_postpc', line 29, column 2 to column 24)",
  " (in 'blouchOU_direct_postpc', line 30, column 2 to column 14)",
  " (in 'blouchOU_direct_postpc', line 31, column 2 to column 20)",
  " (in 'blouchOU_direct_postpc', line 32, column 2 to column 14)",
  " (in 'blouchOU_direct_postpc', line 33, column 2 to column 23)",
  " (in 'blouchOU_direct_postpc', line 57, column 2 to column 16)",
  " (in 'blouchOU_direct_postpc', line 58, column 2 to column 18)",
  " (in 'blouchOU_direct_postpc', line 59, column 2 to column 15)",
  " (in 'blouchOU_direct_postpc', line 60, column 2 to column 18)",
  " (in 'blouchOU_direct_postpc', line 61, column 2 to column 22)",
  " (in 'blouchOU_direct_postpc', line 62, column 2 to column 37)",
  " (in 'blouchOU_direct_postpc', line 63, column 2 to column 21)",
  " (in 'blouchOU_direct_postpc', line 64, column 2 to column 34)",
  " (in 'blouchOU_direct_postpc', line 65, column 2 to column 30)",
  " (in 'blouchOU_direct_postpc', line 66, column 2 to column 21)",
  " (in 'blouchOU_direct_postpc', line 67, column 2 to column 46)",
  " (in 'blouchOU_direct_postpc', line 69, column 4 to column 51)",
  " (in 'blouchOU_direct_postpc', line 68, column 15 to line 70, column 3)",
  " (in 'blouchOU_direct_postpc', line 68, column 2 to line 70, column 3)",
  " (in 'blouchOU_direct_postpc', line 36, column 9 to column 10)",
  " (in 'blouchOU_direct_postpc', line 36, column 2 to column 15)",
  " (in 'blouchOU_direct_postpc', line 37, column 2 to column 9)",
  " (in 'blouchOU_direct_postpc', line 38, column 9 to column 10)",
  " (in 'blouchOU_direct_postpc', line 38, column 11 to column 12)",
  " (in 'blouchOU_direct_postpc', line 38, column 2 to column 16)",
  " (in 'blouchOU_direct_postpc', line 39, column 9 to column 10)",
  " (in 'blouchOU_direct_postpc', line 39, column 11 to column 12)",
  " (in 'blouchOU_direct_postpc', line 39, column 2 to column 18)",
  " (in 'blouchOU_direct_postpc', line 40, column 2 to column 37)",
  " (in 'blouchOU_direct_postpc', line 41, column 2 to column 55)",
  " (in 'blouchOU_direct_postpc', line 42, column 2 to column 42)",
  " (in 'blouchOU_direct_postpc', line 43, column 2 to column 64)",
  " (in 'blouchOU_direct_postpc', line 44, column 2 to column 58)",
  " (in 'blouchOU_direct_postpc', line 45, column 2 to column 16)",
  " (in 'blouchOU_direct_postpc', line 46, column 2 to column 34)",
  " (in 'blouchOU_direct_postpc', line 47, column 2 to column 30)",
  " (in 'blouchOU_direct_postpc', line 49, column 4 to column 37)",
  " (in 'blouchOU_direct_postpc', line 50, column 4 to column 55)",
  " (in 'blouchOU_direct_postpc', line 48, column 22 to line 51, column 3)",
  " (in 'blouchOU_direct_postpc', line 48, column 2 to line 51, column 3)",
  " (in 'blouchOU_direct_postpc', line 52, column 2 to column 21)",
  " (in 'blouchOU_direct_postpc', line 53, column 2 to column 53)",
  " (in 'blouchOU_direct_postpc', line 54, column 2 to column 44)",
  " (in 'blouchOU_direct_postpc', line 14, column 2 to column 8)",
  " (in 'blouchOU_direct_postpc', line 15, column 2 to column 15)",
  " (in 'blouchOU_direct_postpc', line 16, column 9 to column 10)",
  " (in 'blouchOU_direct_postpc', line 16, column 2 to column 18)",
  " (in 'blouchOU_direct_postpc', line 17, column 9 to column 10)",
  " (in 'blouchOU_direct_postpc', line 17, column 11 to column 19)",
  " (in 'blouchOU_direct_postpc', line 17, column 2 to column 27)",
  " (in 'blouchOU_direct_postpc', line 18, column 9 to column 10)",
  " (in 'blouchOU_direct_postpc', line 18, column 2 to column 20)",
  " (in 'blouchOU_direct_postpc', line 19, column 9 to column 10)",
  " (in 'blouchOU_direct_postpc', line 19, column 11 to column 19)",
  " (in 'blouchOU_direct_postpc', line 19, column 2 to column 29)",
  " (in 'blouchOU_direct_postpc', line 20, column 9 to column 10)",
  " (in 'blouchOU_direct_postpc', line 20, column 11 to column 12)",
  " (in 'blouchOU_direct_postpc', line 20, column 2 to column 17)",
  " (in 'blouchOU_direct_postpc', line 21, column 9 to column 10)",
  " (in 'blouchOU_direct_postpc', line 21, column 11 to column 12)",
  " (in 'blouchOU_direct_postpc', line 21, column 2 to column 18)",
  " (in 'blouchOU_direct_postpc', line 22, column 2 to column 21)",
  " (in 'blouchOU_direct_postpc', line 23, column 2 to column 16)",
  " (in 'blouchOU_direct_postpc', line 24, column 2 to column 25)",
  " (in 'blouchOU_direct_postpc', line 25, column 2 to column 23)",
  " (in 'blouchOU_direct_postpc', line 29, column 9 to column 17)",
  " (in 'blouchOU_direct_postpc', line 32, column 9 to column 10)",
  " (in 'blouchOU_direct_postpc', line 33, column 9 to column 10)",
  " (in 'blouchOU_direct_postpc', line 33, column 11 to column 19)",
  " (in 'blouchOU_direct_postpc', line 57, column 9 to column 10)",
  " (in 'blouchOU_direct_postpc', line 57, column 11 to column 12)",
  " (in 'blouchOU_direct_postpc', line 58, column 9 to column 10)",
  " (in 'blouchOU_direct_postpc', line 58, column 11 to column 12)",
  " (in 'blouchOU_direct_postpc', line 59, column 9 to column 10)",
  " (in 'blouchOU_direct_postpc', line 60, column 9 to column 10)",
  " (in 'blouchOU_direct_postpc', line 61, column 9 to column 10)",
  " (in 'blouchOU_direct_postpc', line 7, column 4 to column 24)",
  " (in 'blouchOU_direct_postpc', line 8, column 11 to column 12)",
  " (in 'blouchOU_direct_postpc', line 8, column 14 to column 15)",
  " (in 'blouchOU_direct_postpc', line 8, column 4 to column 20)",
  " (in 'blouchOU_direct_postpc', line 9, column 4 to column 72)",
  " (in 'blouchOU_direct_postpc', line 10, column 4 to column 14)",
  " (in 'blouchOU_direct_postpc', line 6, column 61 to line 11, column 3)"};
template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<
                                                      std::decay_t<T0__>>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<
                                                      std::decay_t<T1__>>>,
                              stan::is_eigen_matrix_dynamic<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              stan::is_eigen_matrix_dynamic<T3__>,
                              stan::is_vt_not_complex<T3__>>* = nullptr>
Eigen::Matrix<stan::return_type_t<T0__, T1__, stan::base_type_t<T2__>,
                stan::base_type_t<T3__>>,-1,-1>
calc_V(const T0__& a, const T1__& sigma2_y, const T2__& ta_arg__, const T3__&
       tij_arg__, std::ostream* pstream__);
// matrix calc_V(real, real, matrix, matrix)
template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<
                                                      std::decay_t<T0__>>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<
                                                      std::decay_t<T1__>>>,
                              stan::is_eigen_matrix_dynamic<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              stan::is_eigen_matrix_dynamic<T3__>,
                              stan::is_vt_not_complex<T3__>>*>
Eigen::Matrix<stan::return_type_t<T0__, T1__, stan::base_type_t<T2__>,
                stan::base_type_t<T3__>>,-1,-1>
calc_V(const T0__& a, const T1__& sigma2_y, const T2__& ta_arg__, const T3__&
       tij_arg__, std::ostream* pstream__) {
  using local_scalar_t__ = stan::return_type_t<T0__, T1__,
                             stan::base_type_t<T2__>,
                             stan::base_type_t<T3__>>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  const auto& ta = stan::math::to_ref(ta_arg__);
  const auto& tij = stan::math::to_ref(tij_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int N = std::numeric_limits<int>::min();
    current_statement__ = 78;
    N = stan::model::rvalue(stan::math::dims(ta), "dims(ta)",
          stan::model::index_uni(1));
    current_statement__ = 79;
    stan::math::validate_non_negative_index("Vt", "N", N);
    current_statement__ = 80;
    stan::math::validate_non_negative_index("Vt", "N", N);
    Eigen::Matrix<local_scalar_t__,-1,-1> Vt =
      Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N, N, DUMMY_VAR__);
    current_statement__ = 82;
    stan::model::assign(Vt,
      stan::math::multiply((sigma2_y / (2 * a)),
        stan::math::elt_multiply(
          stan::math::subtract(1,
            stan::math::exp(stan::math::multiply((-(2) * a), ta))),
          stan::math::exp(stan::math::multiply(-(a), tij)))),
      "assigning variable Vt");
    current_statement__ = 83;
    return Vt;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
#include <stan_meta_header.hpp>
class model_blouchOU_direct_postpc final : public model_base_crtp<model_blouchOU_direct_postpc> {
private:
  int N;
  int Z_direct;
  Eigen::Matrix<double,-1,1> Y_obs_data__;
  Eigen::Matrix<double,-1,-1> X_obs_data__;
  Eigen::Matrix<double,-1,1> Y_error_data__;
  Eigen::Matrix<double,-1,-1> X_error_data__;
  Eigen::Matrix<double,-1,-1> ta_data__;
  Eigen::Matrix<double,-1,-1> tij_data__;
  Eigen::Matrix<double,-1,1> hl_prior_data__;
  double vy_prior;
  Eigen::Matrix<double,-1,1> optima_prior_data__;
  Eigen::Matrix<double,-1,1> beta_prior_data__;
  Eigen::Map<Eigen::Matrix<double,-1,1>> Y_obs{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X_obs{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> Y_error{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X_error{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> ta{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> tij{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> hl_prior{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> optima_prior{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> beta_prior{nullptr, 0};
public:
  ~model_blouchOU_direct_postpc() {}
  model_blouchOU_direct_postpc(stan::io::var_context& context__, unsigned int
                               random_seed__ = 0, std::ostream*
                               pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    using local_scalar_t__ = double;
    auto base_rng__ = stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_blouchOU_direct_postpc_namespace::model_blouchOU_direct_postpc";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 45;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 45;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 46;
      context__.validate_dims("data initialization", "Z_direct", "int",
        std::vector<size_t>{});
      Z_direct = std::numeric_limits<int>::min();
      current_statement__ = 46;
      Z_direct = context__.vals_i("Z_direct")[(1 - 1)];
      current_statement__ = 47;
      stan::math::validate_non_negative_index("Y_obs", "N", N);
      current_statement__ = 48;
      context__.validate_dims("data initialization", "Y_obs", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      Y_obs_data__ = Eigen::Matrix<double,-1,1>::Constant(N,
                       std::numeric_limits<double>::quiet_NaN());
      new (&Y_obs)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(Y_obs_data__.data(), N);
      {
        std::vector<local_scalar_t__> Y_obs_flat__;
        current_statement__ = 48;
        Y_obs_flat__ = context__.vals_r("Y_obs");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          stan::model::assign(Y_obs, Y_obs_flat__[(pos__ - 1)],
            "assigning variable Y_obs", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 49;
      stan::math::validate_non_negative_index("X_obs", "N", N);
      current_statement__ = 50;
      stan::math::validate_non_negative_index("X_obs", "Z_direct", Z_direct);
      current_statement__ = 51;
      context__.validate_dims("data initialization", "X_obs", "double",
        std::vector<size_t>{static_cast<size_t>(N),
          static_cast<size_t>(Z_direct)});
      X_obs_data__ = Eigen::Matrix<double,-1,-1>::Constant(N, Z_direct,
                       std::numeric_limits<double>::quiet_NaN());
      new (&X_obs)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(X_obs_data__.data(), N,
        Z_direct);
      {
        std::vector<local_scalar_t__> X_obs_flat__;
        current_statement__ = 51;
        X_obs_flat__ = context__.vals_r("X_obs");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= Z_direct; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            stan::model::assign(X_obs, X_obs_flat__[(pos__ - 1)],
              "assigning variable X_obs", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 52;
      stan::math::validate_non_negative_index("Y_error", "N", N);
      current_statement__ = 53;
      context__.validate_dims("data initialization", "Y_error", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      Y_error_data__ = Eigen::Matrix<double,-1,1>::Constant(N,
                         std::numeric_limits<double>::quiet_NaN());
      new (&Y_error)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(Y_error_data__.data(), N);
      {
        std::vector<local_scalar_t__> Y_error_flat__;
        current_statement__ = 53;
        Y_error_flat__ = context__.vals_r("Y_error");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          stan::model::assign(Y_error, Y_error_flat__[(pos__ - 1)],
            "assigning variable Y_error", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 54;
      stan::math::validate_non_negative_index("X_error", "N", N);
      current_statement__ = 55;
      stan::math::validate_non_negative_index("X_error", "Z_direct", Z_direct);
      current_statement__ = 56;
      context__.validate_dims("data initialization", "X_error", "double",
        std::vector<size_t>{static_cast<size_t>(N),
          static_cast<size_t>(Z_direct)});
      X_error_data__ = Eigen::Matrix<double,-1,-1>::Constant(N, Z_direct,
                         std::numeric_limits<double>::quiet_NaN());
      new (&X_error)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(X_error_data__.data(), N,
        Z_direct);
      {
        std::vector<local_scalar_t__> X_error_flat__;
        current_statement__ = 56;
        X_error_flat__ = context__.vals_r("X_error");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= Z_direct; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            stan::model::assign(X_error, X_error_flat__[(pos__ - 1)],
              "assigning variable X_error", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 57;
      stan::math::validate_non_negative_index("ta", "N", N);
      current_statement__ = 58;
      stan::math::validate_non_negative_index("ta", "N", N);
      current_statement__ = 59;
      context__.validate_dims("data initialization", "ta", "double",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(N)});
      ta_data__ = Eigen::Matrix<double,-1,-1>::Constant(N, N,
                    std::numeric_limits<double>::quiet_NaN());
      new (&ta) Eigen::Map<Eigen::Matrix<double,-1,-1>>(ta_data__.data(), N,
        N);
      {
        std::vector<local_scalar_t__> ta_flat__;
        current_statement__ = 59;
        ta_flat__ = context__.vals_r("ta");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            stan::model::assign(ta, ta_flat__[(pos__ - 1)],
              "assigning variable ta", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 60;
      stan::math::validate_non_negative_index("tij", "N", N);
      current_statement__ = 61;
      stan::math::validate_non_negative_index("tij", "N", N);
      current_statement__ = 62;
      context__.validate_dims("data initialization", "tij", "double",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(N)});
      tij_data__ = Eigen::Matrix<double,-1,-1>::Constant(N, N,
                     std::numeric_limits<double>::quiet_NaN());
      new (&tij) Eigen::Map<Eigen::Matrix<double,-1,-1>>(tij_data__.data(),
        N, N);
      {
        std::vector<local_scalar_t__> tij_flat__;
        current_statement__ = 62;
        tij_flat__ = context__.vals_r("tij");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            stan::model::assign(tij, tij_flat__[(pos__ - 1)],
              "assigning variable tij", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 63;
      context__.validate_dims("data initialization", "hl_prior", "double",
        std::vector<size_t>{static_cast<size_t>(2)});
      hl_prior_data__ = Eigen::Matrix<double,-1,1>::Constant(2,
                          std::numeric_limits<double>::quiet_NaN());
      new (&hl_prior)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(hl_prior_data__.data(), 2);
      {
        std::vector<local_scalar_t__> hl_prior_flat__;
        current_statement__ = 63;
        hl_prior_flat__ = context__.vals_r("hl_prior");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          stan::model::assign(hl_prior, hl_prior_flat__[(pos__ - 1)],
            "assigning variable hl_prior", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 64;
      context__.validate_dims("data initialization", "vy_prior", "double",
        std::vector<size_t>{});
      vy_prior = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 64;
      vy_prior = context__.vals_r("vy_prior")[(1 - 1)];
      current_statement__ = 65;
      context__.validate_dims("data initialization", "optima_prior",
        "double", std::vector<size_t>{static_cast<size_t>(2)});
      optima_prior_data__ = Eigen::Matrix<double,-1,1>::Constant(2,
                              std::numeric_limits<double>::quiet_NaN());
      new (&optima_prior)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(optima_prior_data__.data(), 2);
      {
        std::vector<local_scalar_t__> optima_prior_flat__;
        current_statement__ = 65;
        optima_prior_flat__ = context__.vals_r("optima_prior");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          stan::model::assign(optima_prior, optima_prior_flat__[(pos__ - 1)],
            "assigning variable optima_prior", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 66;
      context__.validate_dims("data initialization", "beta_prior", "double",
        std::vector<size_t>{static_cast<size_t>(2)});
      beta_prior_data__ = Eigen::Matrix<double,-1,1>::Constant(2,
                            std::numeric_limits<double>::quiet_NaN());
      new (&beta_prior)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(beta_prior_data__.data(), 2);
      {
        std::vector<local_scalar_t__> beta_prior_flat__;
        current_statement__ = 66;
        beta_prior_flat__ = context__.vals_r("beta_prior");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          stan::model::assign(beta_prior, beta_prior_flat__[(pos__ - 1)],
            "assigning variable beta_prior", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 67;
      stan::math::validate_non_negative_index("beta", "Z_direct", Z_direct);
      current_statement__ = 68;
      stan::math::validate_non_negative_index("Y", "N", N);
      current_statement__ = 69;
      stan::math::validate_non_negative_index("X", "N", N);
      current_statement__ = 70;
      stan::math::validate_non_negative_index("X", "Z_direct", Z_direct);
      current_statement__ = 71;
      stan::math::validate_non_negative_index("V", "N", N);
      current_statement__ = 72;
      stan::math::validate_non_negative_index("V", "N", N);
      current_statement__ = 73;
      stan::math::validate_non_negative_index("L_v", "N", N);
      current_statement__ = 74;
      stan::math::validate_non_negative_index("L_v", "N", N);
      current_statement__ = 75;
      stan::math::validate_non_negative_index("mu", "N", N);
      current_statement__ = 76;
      stan::math::validate_non_negative_index("Y_sim", "N", N);
      current_statement__ = 77;
      stan::math::validate_non_negative_index("Y_sim_obs", "N", N);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + Z_direct + 1 + 1 + N + (N * Z_direct);
  }
  inline std::string model_name() const final {
    return "model_blouchOU_direct_postpc";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.37.0-rc3",
             "stancflags = --allow-undefined"};
  }
  // Base log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_not_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_blouchOU_direct_postpc_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto hl =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 2;
      auto beta =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(Z_direct);
      current_statement__ = 3;
      auto optima = in__.template read<local_scalar_t__>();
      current_statement__ = 4;
      auto vy =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 5;
      auto Y = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(N);
      current_statement__ = 6;
      auto X =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,-1>>(N,
          Z_direct);
      {
        current_statement__ = 21;
        stan::math::validate_non_negative_index("mu", "N", N);
        Eigen::Matrix<local_scalar_t__,-1,1> mu =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
        local_scalar_t__ a = DUMMY_VAR__;
        current_statement__ = 24;
        stan::math::validate_non_negative_index("V", "N", N);
        current_statement__ = 25;
        stan::math::validate_non_negative_index("V", "N", N);
        Eigen::Matrix<local_scalar_t__,-1,-1> V =
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N, N, DUMMY_VAR__);
        current_statement__ = 27;
        stan::math::validate_non_negative_index("L_v", "N", N);
        current_statement__ = 28;
        stan::math::validate_non_negative_index("L_v", "N", N);
        Eigen::Matrix<local_scalar_t__,-1,-1> L_v =
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N, N, DUMMY_VAR__);
        local_scalar_t__ sigma2_y = DUMMY_VAR__;
        current_statement__ = 30;
        sigma2_y = (vy * (2 * (stan::math::log(2) / hl)));
        current_statement__ = 31;
        lp_accum__.add(stan::math::lognormal_lpdf<false>(hl,
                         stan::model::rvalue(hl_prior, "hl_prior",
                           stan::model::index_uni(1)),
                         stan::model::rvalue(hl_prior, "hl_prior",
                           stan::model::index_uni(2))));
        current_statement__ = 32;
        lp_accum__.add(stan::math::exponential_lpdf<false>(vy, vy_prior));
        current_statement__ = 33;
        lp_accum__.add(stan::math::normal_lpdf<false>(optima,
                         stan::model::rvalue(optima_prior, "optima_prior",
                           stan::model::index_uni(1)),
                         stan::model::rvalue(optima_prior, "optima_prior",
                           stan::model::index_uni(2))));
        current_statement__ = 34;
        lp_accum__.add(stan::math::normal_lpdf<false>(beta,
                         stan::model::rvalue(beta_prior, "beta_prior",
                           stan::model::index_uni(1)),
                         stan::model::rvalue(beta_prior, "beta_prior",
                           stan::model::index_uni(2))));
        current_statement__ = 35;
        a = (stan::math::log(2) / hl);
        current_statement__ = 36;
        stan::model::assign(V, calc_V(a, sigma2_y, ta, tij, pstream__),
          "assigning variable V");
        current_statement__ = 37;
        stan::model::assign(L_v, stan::math::cholesky_decompose(V),
          "assigning variable L_v");
        current_statement__ = 41;
        for (int i = 1; i <= Z_direct; ++i) {
          current_statement__ = 38;
          lp_accum__.add(stan::math::normal_lpdf<false>(
                           stan::model::rvalue(X, "X",
                             stan::model::index_omni(),
                             stan::model::index_uni(i)), 0, 1));
          current_statement__ = 39;
          lp_accum__.add(stan::math::normal_lpdf<false>(
                           stan::model::rvalue(X_obs, "X_obs",
                             stan::model::index_omni(),
                             stan::model::index_uni(i)),
                           stan::model::rvalue(X, "X",
                             stan::model::index_omni(),
                             stan::model::index_uni(i)),
                           stan::model::rvalue(X_error, "X_error",
                             stan::model::index_omni(),
                             stan::model::index_uni(i))));
        }
        current_statement__ = 42;
        stan::model::assign(mu,
          stan::math::add(optima, stan::math::multiply(X, beta)),
          "assigning variable mu");
        current_statement__ = 43;
        lp_accum__.add(stan::math::multi_normal_cholesky_lpdf<false>(Y, mu,
                         L_v));
        current_statement__ = 44;
        lp_accum__.add(stan::math::normal_lpdf<false>(Y_obs, Y, Y_error));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  // Reverse mode autodiff log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_blouchOU_direct_postpc_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto hl =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 2;
      auto beta =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(Z_direct);
      current_statement__ = 3;
      auto optima = in__.template read<local_scalar_t__>();
      current_statement__ = 4;
      auto vy =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 5;
      auto Y = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(N);
      current_statement__ = 6;
      auto X =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,-1>>(N,
          Z_direct);
      {
        current_statement__ = 21;
        stan::math::validate_non_negative_index("mu", "N", N);
        Eigen::Matrix<local_scalar_t__,-1,1> mu =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
        local_scalar_t__ a = DUMMY_VAR__;
        current_statement__ = 24;
        stan::math::validate_non_negative_index("V", "N", N);
        current_statement__ = 25;
        stan::math::validate_non_negative_index("V", "N", N);
        Eigen::Matrix<local_scalar_t__,-1,-1> V =
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N, N, DUMMY_VAR__);
        current_statement__ = 27;
        stan::math::validate_non_negative_index("L_v", "N", N);
        current_statement__ = 28;
        stan::math::validate_non_negative_index("L_v", "N", N);
        Eigen::Matrix<local_scalar_t__,-1,-1> L_v =
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N, N, DUMMY_VAR__);
        local_scalar_t__ sigma2_y = DUMMY_VAR__;
        current_statement__ = 30;
        sigma2_y = (vy * (2 * (stan::math::log(2) / hl)));
        current_statement__ = 31;
        lp_accum__.add(stan::math::lognormal_lpdf<false>(hl,
                         stan::model::rvalue(hl_prior, "hl_prior",
                           stan::model::index_uni(1)),
                         stan::model::rvalue(hl_prior, "hl_prior",
                           stan::model::index_uni(2))));
        current_statement__ = 32;
        lp_accum__.add(stan::math::exponential_lpdf<false>(vy, vy_prior));
        current_statement__ = 33;
        lp_accum__.add(stan::math::normal_lpdf<false>(optima,
                         stan::model::rvalue(optima_prior, "optima_prior",
                           stan::model::index_uni(1)),
                         stan::model::rvalue(optima_prior, "optima_prior",
                           stan::model::index_uni(2))));
        current_statement__ = 34;
        lp_accum__.add(stan::math::normal_lpdf<false>(beta,
                         stan::model::rvalue(beta_prior, "beta_prior",
                           stan::model::index_uni(1)),
                         stan::model::rvalue(beta_prior, "beta_prior",
                           stan::model::index_uni(2))));
        current_statement__ = 35;
        a = (stan::math::log(2) / hl);
        current_statement__ = 36;
        stan::model::assign(V, calc_V(a, sigma2_y, ta, tij, pstream__),
          "assigning variable V");
        current_statement__ = 37;
        stan::model::assign(L_v, stan::math::cholesky_decompose(V),
          "assigning variable L_v");
        current_statement__ = 41;
        for (int i = 1; i <= Z_direct; ++i) {
          current_statement__ = 38;
          lp_accum__.add(stan::math::normal_lpdf<false>(
                           stan::model::rvalue(X, "X",
                             stan::model::index_omni(),
                             stan::model::index_uni(i)), 0, 1));
          current_statement__ = 39;
          lp_accum__.add(stan::math::normal_lpdf<false>(
                           stan::model::rvalue(X_obs, "X_obs",
                             stan::model::index_omni(),
                             stan::model::index_uni(i)),
                           stan::model::rvalue(X, "X",
                             stan::model::index_omni(),
                             stan::model::index_uni(i)),
                           stan::model::rvalue(X_error, "X_error",
                             stan::model::index_omni(),
                             stan::model::index_uni(i))));
        }
        current_statement__ = 42;
        stan::model::assign(mu,
          stan::math::add(optima, stan::math::multiply(X, beta)),
          "assigning variable mu");
        current_statement__ = 43;
        lp_accum__.add(stan::math::multi_normal_cholesky_lpdf<false>(Y, mu,
                         L_v));
        current_statement__ = 44;
        lp_accum__.add(stan::math::normal_lpdf<false>(Y_obs, Y, Y_error));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    // suppress unused var warning
    (void) jacobian__;
    static constexpr const char* function__ =
      "model_blouchOU_direct_postpc_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto hl =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 2;
      auto beta =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(Z_direct);
      current_statement__ = 3;
      auto optima = in__.template read<local_scalar_t__>();
      current_statement__ = 4;
      auto vy =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 5;
      auto Y = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(N);
      current_statement__ = 6;
      auto X =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,-1>>(N,
          Z_direct);
      out__.write(hl);
      out__.write(beta);
      out__.write(optima);
      out__.write(vy);
      out__.write(Y);
      out__.write(X);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      Eigen::Matrix<double,-1,-1> V =
        Eigen::Matrix<double,-1,-1>::Constant(N, N,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,-1> L_v =
        Eigen::Matrix<double,-1,-1>::Constant(N, N,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> mu =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> Y_sim =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> Y_sim_obs =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      double sigma2_y = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 12;
      sigma2_y = (vy * (2 * (stan::math::log(2) / hl)));
      double a = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 13;
      a = (stan::math::log(2) / hl);
      current_statement__ = 14;
      stan::model::assign(V, calc_V(a, sigma2_y, ta, tij, pstream__),
        "assigning variable V");
      current_statement__ = 15;
      stan::model::assign(L_v, stan::math::cholesky_decompose(V),
        "assigning variable L_v");
      current_statement__ = 16;
      stan::model::assign(mu,
        stan::math::add(optima, stan::math::multiply(X, beta)),
        "assigning variable mu");
      current_statement__ = 17;
      stan::model::assign(Y_sim,
        stan::math::multi_normal_cholesky_rng(mu, L_v, base_rng__),
        "assigning variable Y_sim");
      current_statement__ = 20;
      for (int i = 1; i <= N; ++i) {
        current_statement__ = 18;
        stan::model::assign(Y_sim_obs,
          stan::math::normal_rng(
            stan::model::rvalue(Y_sim, "Y_sim", stan::model::index_uni(i)),
            stan::model::rvalue(Y_error, "Y_error", stan::model::index_uni(i)),
            base_rng__), "assigning variable Y_sim_obs",
          stan::model::index_uni(i));
      }
      out__.write(V);
      out__.write(L_v);
      out__.write(mu);
      out__.write(Y_sim);
      out__.write(Y_sim_obs);
      out__.write(sigma2_y);
      out__.write(a);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      local_scalar_t__ hl = DUMMY_VAR__;
      current_statement__ = 1;
      hl = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, hl);
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(Z_direct, DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(beta,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(Z_direct),
        "assigning variable beta");
      out__.write(beta);
      local_scalar_t__ optima = DUMMY_VAR__;
      current_statement__ = 3;
      optima = in__.read<local_scalar_t__>();
      out__.write(optima);
      local_scalar_t__ vy = DUMMY_VAR__;
      current_statement__ = 4;
      vy = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, vy);
      Eigen::Matrix<local_scalar_t__,-1,1> Y =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      current_statement__ = 5;
      stan::model::assign(Y,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(N),
        "assigning variable Y");
      out__.write(Y);
      Eigen::Matrix<local_scalar_t__,-1,-1> X =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N, Z_direct,
          DUMMY_VAR__);
      current_statement__ = 6;
      stan::model::assign(X,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,-1>>(N, Z_direct),
        "assigning variable X");
      out__.write(X);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "hl", "double",
        std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "beta", "double",
        std::vector<size_t>{static_cast<size_t>(Z_direct)});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "optima", "double",
        std::vector<size_t>{});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "vy", "double",
        std::vector<size_t>{});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization", "Y", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      current_statement__ = 6;
      context__.validate_dims("parameter initialization", "X", "double",
        std::vector<size_t>{static_cast<size_t>(N),
          static_cast<size_t>(Z_direct)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ hl = DUMMY_VAR__;
      current_statement__ = 1;
      hl = context__.vals_r("hl")[(1 - 1)];
      out__.write_free_lb(0, hl);
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(Z_direct, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> beta_flat__;
        current_statement__ = 2;
        beta_flat__ = context__.vals_r("beta");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= Z_direct; ++sym1__) {
          stan::model::assign(beta, beta_flat__[(pos__ - 1)],
            "assigning variable beta", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write(beta);
      local_scalar_t__ optima = DUMMY_VAR__;
      current_statement__ = 3;
      optima = context__.vals_r("optima")[(1 - 1)];
      out__.write(optima);
      local_scalar_t__ vy = DUMMY_VAR__;
      current_statement__ = 4;
      vy = context__.vals_r("vy")[(1 - 1)];
      out__.write_free_lb(0, vy);
      Eigen::Matrix<local_scalar_t__,-1,1> Y =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> Y_flat__;
        current_statement__ = 5;
        Y_flat__ = context__.vals_r("Y");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          stan::model::assign(Y, Y_flat__[(pos__ - 1)],
            "assigning variable Y", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write(Y);
      Eigen::Matrix<local_scalar_t__,-1,-1> X =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N, Z_direct,
          DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> X_flat__;
        current_statement__ = 6;
        X_flat__ = context__.vals_r("X");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= Z_direct; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            stan::model::assign(X, X_flat__[(pos__ - 1)],
              "assigning variable X", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write(X);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"hl", "beta", "optima", "vy", "Y",
                "X"};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      std::vector<std::string>
        temp{"V", "L_v", "mu", "Y_sim", "Y_sim_obs", "sigma2_y", "a"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(Z_direct)},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(N)},
                std::vector<size_t>{static_cast<size_t>(N),
                  static_cast<size_t>(Z_direct)}};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(N),
               static_cast<size_t>(N)},
             std::vector<size_t>{static_cast<size_t>(N),
               static_cast<size_t>(N)},
             std::vector<size_t>{static_cast<size_t>(N)},
             std::vector<size_t>{static_cast<size_t>(N)},
             std::vector<size_t>{static_cast<size_t>(N)},
             std::vector<size_t>{}, std::vector<size_t>{}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "hl");
    for (int sym1__ = 1; sym1__ <= Z_direct; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "optima");
    param_names__.emplace_back(std::string() + "vy");
    for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
      param_names__.emplace_back(std::string() + "Y" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= Z_direct; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
        param_names__.emplace_back(std::string() + "X" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          param_names__.emplace_back(std::string() + "V" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          param_names__.emplace_back(std::string() + "L_v" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "mu" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "Y_sim" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "Y_sim_obs" + '.' +
          std::to_string(sym1__));
      }
      param_names__.emplace_back(std::string() + "sigma2_y");
      param_names__.emplace_back(std::string() + "a");
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "hl");
    for (int sym1__ = 1; sym1__ <= Z_direct; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "optima");
    param_names__.emplace_back(std::string() + "vy");
    for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
      param_names__.emplace_back(std::string() + "Y" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= Z_direct; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
        param_names__.emplace_back(std::string() + "X" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          param_names__.emplace_back(std::string() + "V" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          param_names__.emplace_back(std::string() + "L_v" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "mu" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "Y_sim" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "Y_sim_obs" + '.' +
          std::to_string(sym1__));
      }
      param_names__.emplace_back(std::string() + "sigma2_y");
      param_names__.emplace_back(std::string() + "a");
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"hl\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(Z_direct) + "},\"block\":\"parameters\"},{\"name\":\"optima\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"vy\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"Y\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"parameters\"},{\"name\":\"X\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(N) + ",\"cols\":" + std::to_string(Z_direct) + "},\"block\":\"parameters\"},{\"name\":\"V\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(N) + ",\"cols\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"},{\"name\":\"L_v\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(N) + ",\"cols\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"},{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"},{\"name\":\"Y_sim\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"},{\"name\":\"Y_sim_obs\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"},{\"name\":\"sigma2_y\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"a\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"hl\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(Z_direct) + "},\"block\":\"parameters\"},{\"name\":\"optima\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"vy\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"Y\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"parameters\"},{\"name\":\"X\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(N) + ",\"cols\":" + std::to_string(Z_direct) + "},\"block\":\"parameters\"},{\"name\":\"V\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(N) + ",\"cols\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"},{\"name\":\"L_v\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(N) + ",\"cols\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"},{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"},{\"name\":\"Y_sim\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"},{\"name\":\"Y_sim_obs\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"},{\"name\":\"sigma2_y\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"a\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((((1 + Z_direct) + 1) + 1) + N) + (N *
      Z_direct));
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * ((((((((N *
      N) + (N * N)) + N) + N) + N) + 1) + 1));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((((1 + Z_direct) + 1) + 1) + N) + (N *
      Z_direct));
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * ((((((((N *
      N) + (N * N)) + N) + N) + N) + 1) + 1));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_blouchOU_direct_postpc_namespace::model_blouchOU_direct_postpc;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_blouchOU_direct_postpc_namespace::profiles__;
}
#endif
#endif
