// Generated by rstantools.  Do not edit by hand.

/*
    blouch is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    blouch is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with blouch.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_blouchOU_reg_direct_ve_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 169> locations_array__ =
  {" (found before start of program)",
  " (in 'blouchOU_reg_direct_ve', line 89, column 2 to column 19)",
  " (in 'blouchOU_reg_direct_ve', line 90, column 2 to column 20)",
  " (in 'blouchOU_reg_direct_ve', line 91, column 2 to column 30)",
  " (in 'blouchOU_reg_direct_ve', line 92, column 2 to column 14)",
  " (in 'blouchOU_reg_direct_ve', line 93, column 2 to column 23)",
  " (in 'blouchOU_reg_direct_ve', line 94, column 2 to column 23)",
  " (in 'blouchOU_reg_direct_ve', line 136, column 2 to column 16)",
  " (in 'blouchOU_reg_direct_ve', line 137, column 2 to column 20)",
  " (in 'blouchOU_reg_direct_ve', line 138, column 2 to column 32)",
  " (in 'blouchOU_reg_direct_ve', line 139, column 2 to column 15)",
  " (in 'blouchOU_reg_direct_ve', line 140, column 2 to column 11)",
  " (in 'blouchOU_reg_direct_ve', line 141, column 2 to column 16)",
  " (in 'blouchOU_reg_direct_ve', line 142, column 2 to column 15)",
  " (in 'blouchOU_reg_direct_ve', line 143, column 2 to column 11)",
  " (in 'blouchOU_reg_direct_ve', line 144, column 2 to column 20)",
  " (in 'blouchOU_reg_direct_ve', line 145, column 2 to column 37)",
  " (in 'blouchOU_reg_direct_ve', line 146, column 2 to column 21)",
  " (in 'blouchOU_reg_direct_ve', line 148, column 2 to column 41)",
  " (in 'blouchOU_reg_direct_ve', line 149, column 2 to column 95)",
  " (in 'blouchOU_reg_direct_ve', line 150, column 2 to column 21)",
  " (in 'blouchOU_reg_direct_ve', line 152, column 6 to column 65)",
  " (in 'blouchOU_reg_direct_ve', line 151, column 15 to line 153, column 5)",
  " (in 'blouchOU_reg_direct_ve', line 151, column 2 to line 153, column 5)",
  " (in 'blouchOU_reg_direct_ve', line 155, column 6 to column 30)",
  " (in 'blouchOU_reg_direct_ve', line 156, column 6 to column 28)",
  " (in 'blouchOU_reg_direct_ve', line 157, column 6 to column 30)",
  " (in 'blouchOU_reg_direct_ve', line 158, column 6 to column 27)",
  " (in 'blouchOU_reg_direct_ve', line 160, column 6 to column 75)",
  " (in 'blouchOU_reg_direct_ve', line 154, column 15 to line 161, column 7)",
  " (in 'blouchOU_reg_direct_ve', line 154, column 2 to line 161, column 7)",
  " (in 'blouchOU_reg_direct_ve', line 99, column 9 to column 10)",
  " (in 'blouchOU_reg_direct_ve', line 99, column 11 to column 12)",
  " (in 'blouchOU_reg_direct_ve', line 99, column 2 to column 16)",
  " (in 'blouchOU_reg_direct_ve', line 100, column 9 to column 10)",
  " (in 'blouchOU_reg_direct_ve', line 100, column 2 to column 15)",
  " (in 'blouchOU_reg_direct_ve', line 101, column 9 to column 10)",
  " (in 'blouchOU_reg_direct_ve', line 101, column 11 to column 12)",
  " (in 'blouchOU_reg_direct_ve', line 101, column 2 to column 18)",
  " (in 'blouchOU_reg_direct_ve', line 102, column 2 to column 21)",
  " (in 'blouchOU_reg_direct_ve', line 103, column 2 to column 37)",
  " (in 'blouchOU_reg_direct_ve', line 104, column 9 to column 10)",
  " (in 'blouchOU_reg_direct_ve', line 104, column 11 to column 16)",
  " (in 'blouchOU_reg_direct_ve', line 104, column 2 to column 32)",
  " (in 'blouchOU_reg_direct_ve', line 106, column 2 to column 55)",
  " (in 'blouchOU_reg_direct_ve', line 108, column 2 to column 42)",
  " (in 'blouchOU_reg_direct_ve', line 110, column 2 to column 64)",
  " (in 'blouchOU_reg_direct_ve', line 114, column 4 to column 64)",
  " (in 'blouchOU_reg_direct_ve', line 112, column 24 to line 115, column 3)",
  " (in 'blouchOU_reg_direct_ve', line 112, column 2 to line 115, column 3)",
  " (in 'blouchOU_reg_direct_ve', line 118, column 4 to column 37)",
  " (in 'blouchOU_reg_direct_ve', line 120, column 4 to column 55)",
  " (in 'blouchOU_reg_direct_ve', line 116, column 24 to line 121, column 3)",
  " (in 'blouchOU_reg_direct_ve', line 116, column 2 to line 121, column 3)",
  " (in 'blouchOU_reg_direct_ve', line 122, column 2 to column 95)",
  " (in 'blouchOU_reg_direct_ve', line 123, column 2 to column 41)",
  " (in 'blouchOU_reg_direct_ve', line 124, column 2 to column 30)",
  " (in 'blouchOU_reg_direct_ve', line 126, column 6 to column 65)",
  " (in 'blouchOU_reg_direct_ve', line 125, column 15 to line 128, column 5)",
  " (in 'blouchOU_reg_direct_ve', line 125, column 2 to line 128, column 5)",
  " (in 'blouchOU_reg_direct_ve', line 132, column 2 to column 53)",
  " (in 'blouchOU_reg_direct_ve', line 133, column 2 to column 44)",
  " (in 'blouchOU_reg_direct_ve', line 64, column 2 to column 8)",
  " (in 'blouchOU_reg_direct_ve', line 65, column 2 to column 12)",
  " (in 'blouchOU_reg_direct_ve', line 66, column 2 to column 15)",
  " (in 'blouchOU_reg_direct_ve', line 67, column 2 to column 16)",
  " (in 'blouchOU_reg_direct_ve', line 68, column 2 to column 19)",
  " (in 'blouchOU_reg_direct_ve', line 69, column 9 to column 10)",
  " (in 'blouchOU_reg_direct_ve', line 69, column 2 to column 18)",
  " (in 'blouchOU_reg_direct_ve', line 70, column 9 to column 10)",
  " (in 'blouchOU_reg_direct_ve', line 70, column 11 to column 19)",
  " (in 'blouchOU_reg_direct_ve', line 70, column 2 to column 27)",
  " (in 'blouchOU_reg_direct_ve', line 71, column 9 to column 10)",
  " (in 'blouchOU_reg_direct_ve', line 71, column 2 to column 20)",
  " (in 'blouchOU_reg_direct_ve', line 72, column 9 to column 10)",
  " (in 'blouchOU_reg_direct_ve', line 72, column 11 to column 20)",
  " (in 'blouchOU_reg_direct_ve', line 72, column 2 to column 30)",
  " (in 'blouchOU_reg_direct_ve', line 73, column 9 to column 10)",
  " (in 'blouchOU_reg_direct_ve', line 73, column 11 to column 12)",
  " (in 'blouchOU_reg_direct_ve', line 73, column 2 to column 17)",
  " (in 'blouchOU_reg_direct_ve', line 74, column 9 to column 10)",
  " (in 'blouchOU_reg_direct_ve', line 74, column 11 to column 12)",
  " (in 'blouchOU_reg_direct_ve', line 74, column 2 to column 18)",
  " (in 'blouchOU_reg_direct_ve', line 75, column 9 to column 10)",
  " (in 'blouchOU_reg_direct_ve', line 75, column 11 to column 12)",
  " (in 'blouchOU_reg_direct_ve', line 75, column 2 to column 18)",
  " (in 'blouchOU_reg_direct_ve', line 76, column 9 to column 10)",
  " (in 'blouchOU_reg_direct_ve', line 76, column 2 to column 19)",
  " (in 'blouchOU_reg_direct_ve', line 77, column 9 to column 10)",
  " (in 'blouchOU_reg_direct_ve', line 77, column 12 to column 24)",
  " (in 'blouchOU_reg_direct_ve', line 77, column 2 to column 38)",
  " (in 'blouchOU_reg_direct_ve', line 78, column 9 to column 10)",
  " (in 'blouchOU_reg_direct_ve', line 78, column 12 to column 24)",
  " (in 'blouchOU_reg_direct_ve', line 78, column 2 to column 32)",
  " (in 'blouchOU_reg_direct_ve', line 79, column 9 to column 10)",
  " (in 'blouchOU_reg_direct_ve', line 79, column 12 to column 24)",
  " (in 'blouchOU_reg_direct_ve', line 79, column 2 to column 32)",
  " (in 'blouchOU_reg_direct_ve', line 80, column 9 to column 10)",
  " (in 'blouchOU_reg_direct_ve', line 80, column 12 to column 24)",
  " (in 'blouchOU_reg_direct_ve', line 80, column 2 to column 36)",
  " (in 'blouchOU_reg_direct_ve', line 81, column 12 to column 13)",
  " (in 'blouchOU_reg_direct_ve', line 81, column 2 to column 15)",
  " (in 'blouchOU_reg_direct_ve', line 82, column 15 to column 16)",
  " (in 'blouchOU_reg_direct_ve', line 82, column 2 to column 18)",
  " (in 'blouchOU_reg_direct_ve', line 83, column 2 to column 21)",
  " (in 'blouchOU_reg_direct_ve', line 84, column 2 to column 16)",
  " (in 'blouchOU_reg_direct_ve', line 85, column 2 to column 25)",
  " (in 'blouchOU_reg_direct_ve', line 86, column 2 to column 23)",
  " (in 'blouchOU_reg_direct_ve', line 91, column 9 to column 14)",
  " (in 'blouchOU_reg_direct_ve', line 91, column 15 to column 23)",
  " (in 'blouchOU_reg_direct_ve', line 92, column 9 to column 10)",
  " (in 'blouchOU_reg_direct_ve', line 93, column 9 to column 10)",
  " (in 'blouchOU_reg_direct_ve', line 93, column 11 to column 19)",
  " (in 'blouchOU_reg_direct_ve', line 94, column 9 to column 14)",
  " (in 'blouchOU_reg_direct_ve', line 136, column 9 to column 10)",
  " (in 'blouchOU_reg_direct_ve', line 136, column 11 to column 12)",
  " (in 'blouchOU_reg_direct_ve', line 137, column 9 to column 10)",
  " (in 'blouchOU_reg_direct_ve', line 137, column 11 to column 12)",
  " (in 'blouchOU_reg_direct_ve', line 138, column 9 to column 10)",
  " (in 'blouchOU_reg_direct_ve', line 138, column 11 to column 16)",
  " (in 'blouchOU_reg_direct_ve', line 139, column 9 to column 10)",
  " (in 'blouchOU_reg_direct_ve', line 144, column 9 to column 10)",
  " (in 'blouchOU_reg_direct_ve', line 8, column 2 to column 12)",
  " (in 'blouchOU_reg_direct_ve', line 11, column 6 to column 13)",
  " (in 'blouchOU_reg_direct_ve', line 10, column 4 to line 11, column 13)",
  " (in 'blouchOU_reg_direct_ve', line 9, column 2 to line 11, column 13)",
  " (in 'blouchOU_reg_direct_ve', line 12, column 2 to column 12)",
  " (in 'blouchOU_reg_direct_ve', line 7, column 36 to line 13, column 3)",
  " (in 'blouchOU_reg_direct_ve', line 16, column 24 to column 41)",
  " (in 'blouchOU_reg_direct_ve', line 16, column 4 to column 43)",
  " (in 'blouchOU_reg_direct_ve', line 17, column 4 to column 16)",
  " (in 'blouchOU_reg_direct_ve', line 21, column 8 to column 33)",
  " (in 'blouchOU_reg_direct_ve', line 22, column 8 to column 17)",
  " (in 'blouchOU_reg_direct_ve', line 20, column 21 to line 23, column 9)",
  " (in 'blouchOU_reg_direct_ve', line 20, column 6 to line 23, column 9)",
  " (in 'blouchOU_reg_direct_ve', line 19, column 30 to line 24, column 7)",
  " (in 'blouchOU_reg_direct_ve', line 19, column 4 to line 24, column 7)",
  " (in 'blouchOU_reg_direct_ve', line 25, column 4 to column 28)",
  " (in 'blouchOU_reg_direct_ve', line 15, column 38 to line 26, column 3)",
  " (in 'blouchOU_reg_direct_ve', line 28, column 11 to column 16)",
  " (in 'blouchOU_reg_direct_ve', line 28, column 4 to column 95)",
  " (in 'blouchOU_reg_direct_ve', line 29, column 4 to column 20)",
  " (in 'blouchOU_reg_direct_ve', line 27, column 88 to line 30, column 3)",
  " (in 'blouchOU_reg_direct_ve', line 34, column 11 to column 16)",
  " (in 'blouchOU_reg_direct_ve', line 34, column 4 to column 109)",
  " (in 'blouchOU_reg_direct_ve', line 36, column 11 to column 16)",
  " (in 'blouchOU_reg_direct_ve', line 36, column 4 to column 52)",
  " (in 'blouchOU_reg_direct_ve', line 38, column 14 to column 39)",
  " (in 'blouchOU_reg_direct_ve', line 38, column 6 to column 69)",
  " (in 'blouchOU_reg_direct_ve', line 41, column 6 to column 44)",
  " (in 'blouchOU_reg_direct_ve', line 37, column 21 to line 43, column 7)",
  " (in 'blouchOU_reg_direct_ve', line 37, column 4 to line 43, column 7)",
  " (in 'blouchOU_reg_direct_ve', line 44, column 4 to column 25)",
  " (in 'blouchOU_reg_direct_ve', line 32, column 121 to line 45, column 3)",
  " (in 'blouchOU_reg_direct_ve', line 48, column 11 to column 12)",
  " (in 'blouchOU_reg_direct_ve', line 48, column 13 to column 18)",
  " (in 'blouchOU_reg_direct_ve', line 48, column 4 to column 58)",
  " (in 'blouchOU_reg_direct_ve', line 50, column 6 to column 120)",
  " (in 'blouchOU_reg_direct_ve', line 49, column 17 to line 53, column 7)",
  " (in 'blouchOU_reg_direct_ve', line 49, column 4 to line 53, column 7)",
  " (in 'blouchOU_reg_direct_ve', line 54, column 4 to column 26)",
  " (in 'blouchOU_reg_direct_ve', line 47, column 132 to line 55, column 3)",
  " (in 'blouchOU_reg_direct_ve', line 57, column 8 to column 28)",
  " (in 'blouchOU_reg_direct_ve', line 58, column 15 to column 16)",
  " (in 'blouchOU_reg_direct_ve', line 58, column 18 to column 19)",
  " (in 'blouchOU_reg_direct_ve', line 58, column 8 to column 24)",
  " (in 'blouchOU_reg_direct_ve', line 59, column 8 to column 76)",
  " (in 'blouchOU_reg_direct_ve', line 60, column 8 to column 18)",
  " (in 'blouchOU_reg_direct_ve', line 56, column 68 to line 61, column 3)"};
template <typename T0__, typename T1__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_stan_scalar<T1__>>* = nullptr>
int num_matches(const T0__& x_arg__, const T1__& y, std::ostream* pstream__);
template <typename T0__, typename T1__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_stan_scalar<T1__>>* = nullptr>
std::vector<int>
which_equal(const T0__& x_arg__, const T1__& y, std::ostream* pstream__);
template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_col_vector<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              stan::is_stan_scalar<T3__>>* = nullptr>
Eigen::Matrix<stan::promote_args_t<T0__, stan::base_type_t<T1__>,
                stan::base_type_t<T2__>, T3__>,-1,1>
weight_segments(const T0__& a, const T1__& t_beginning_arg__, const T2__&
                t_end_arg__, const T3__& time, const int& nodes,
                std::ostream* pstream__);
template <typename T1__, typename T2__, typename T3__, typename T4__,
          typename T5__,
          stan::require_all_t<stan::is_stan_scalar<T1__>,
                              stan::is_col_vector<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              stan::is_col_vector<T3__>,
                              stan::is_vt_not_complex<T3__>,
                              stan::is_stan_scalar<T4__>,
                              stan::is_col_vector<T5__>,
                              stan::is_vt_not_complex<T5__>>* = nullptr>
Eigen::Matrix<stan::promote_args_t<T1__, stan::base_type_t<T2__>,
                stan::base_type_t<T3__>, T4__, stan::base_type_t<T5__>>,1,-1>
weights_regimes(const int& n_reg, const T1__& a, const T2__&
                t_beginning_arg__, const T3__& t_end_arg__, const T4__& time,
                const T5__& reg_match_arg__, const int& nodes, std::ostream*
                pstream__);
template <typename T2__, typename T3__, typename T4__, typename T5__,
          typename T6__,
          stan::require_all_t<stan::is_stan_scalar<T2__>,
                              stan::is_eigen_matrix_dynamic<T3__>,
                              stan::is_vt_not_complex<T3__>,
                              stan::is_eigen_matrix_dynamic<T4__>,
                              stan::is_vt_not_complex<T4__>,
                              stan::is_eigen_matrix_dynamic<T5__>,
                              stan::is_vt_not_complex<T5__>,
                              stan::is_eigen_matrix_dynamic<T6__>,
                              stan::is_vt_not_complex<T6__>>* = nullptr>
Eigen::Matrix<stan::promote_args_t<T2__, stan::base_type_t<T3__>,
                stan::base_type_t<T4__>, stan::base_type_t<T5__>,
                stan::base_type_t<T6__>>,-1,-1>
calc_optima_matrix(const int& N, const int& n_reg, const T2__& a, const T3__&
                   t_beginning_arg__, const T4__& t_end_arg__, const T5__&
                   times_arg__, const T6__& reg_match_arg__,
                   const std::vector<int>& nodes, std::ostream* pstream__);
template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_eigen_matrix_dynamic<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              stan::is_eigen_matrix_dynamic<T3__>,
                              stan::is_vt_not_complex<T3__>>* = nullptr>
Eigen::Matrix<stan::promote_args_t<T0__, T1__, stan::base_type_t<T2__>,
                stan::base_type_t<T3__>>,-1,-1>
calc_direct_V(const T0__& a, const T1__& sigma2_y, const T2__& ta_arg__,
              const T3__& tij_arg__, std::ostream* pstream__);
template <typename T0__, typename T1__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_stan_scalar<T1__>>*>
int num_matches(const T0__& x_arg__, const T1__& y, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T0__>,
                             T1__>;
  int current_statement__ = 0;
  const auto& x = stan::math::to_ref(x_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int n = std::numeric_limits<int>::min();
    current_statement__ = 122;
    n = 0;
    current_statement__ = 125;
    for (int i = 1; i <= stan::math::rows(x); ++i) {
      current_statement__ = 124;
      if (stan::math::logical_eq(
            stan::model::rvalue(x, "x", stan::model::index_uni(i)), y)) {
        current_statement__ = 123;
        n = (n + 1);
      }
    }
    current_statement__ = 126;
    return n;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T0__, typename T1__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_stan_scalar<T1__>>*>
std::vector<int>
which_equal(const T0__& x_arg__, const T1__& y, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T0__>,
                             T1__>;
  int current_statement__ = 0;
  const auto& x = stan::math::to_ref(x_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 128;
    stan::math::validate_non_negative_index("match_positions",
      "num_matches(x, y)", num_matches(x, y, pstream__));
    std::vector<int> match_positions =
      std::vector<int>(num_matches(x, y, pstream__),
        std::numeric_limits<int>::min());
    int pos = std::numeric_limits<int>::min();
    current_statement__ = 130;
    pos = 1;
    current_statement__ = 136;
    for (int i = 1; i <=
         stan::model::rvalue(stan::math::dims(x), "dims(x)",
           stan::model::index_uni(1)); ++i) {
      current_statement__ = 134;
      if (stan::math::logical_eq(
            stan::model::rvalue(x, "x", stan::model::index_uni(i)), y)) {
        current_statement__ = 131;
        stan::model::assign(match_positions, i,
          "assigning variable match_positions", stan::model::index_uni(pos));
        current_statement__ = 132;
        pos = (pos + 1);
      }
    }
    current_statement__ = 137;
    return match_positions;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_col_vector<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              stan::is_stan_scalar<T3__>>*>
Eigen::Matrix<stan::promote_args_t<T0__, stan::base_type_t<T1__>,
                stan::base_type_t<T2__>, T3__>,-1,1>
weight_segments(const T0__& a, const T1__& t_beginning_arg__, const T2__&
                t_end_arg__, const T3__& time, const int& nodes,
                std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__,
                             stan::base_type_t<T1__>,
                             stan::base_type_t<T2__>, T3__>;
  int current_statement__ = 0;
  const auto& t_beginning = stan::math::to_ref(t_beginning_arg__);
  const auto& t_end = stan::math::to_ref(t_end_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 139;
    stan::math::validate_non_negative_index("weights", "nodes", nodes);
    Eigen::Matrix<local_scalar_t__,-1,1> weights =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nodes, DUMMY_VAR__);
    current_statement__ = 140;
    stan::model::assign(weights,
      stan::math::append_row(
        stan::math::subtract(
          stan::math::exp(stan::math::multiply(-a, t_beginning)),
          stan::math::exp(stan::math::multiply(-a, t_end))),
        stan::math::exp((-a * time))), "assigning variable weights");
    current_statement__ = 141;
    return weights;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T1__, typename T2__, typename T3__, typename T4__,
          typename T5__,
          stan::require_all_t<stan::is_stan_scalar<T1__>,
                              stan::is_col_vector<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              stan::is_col_vector<T3__>,
                              stan::is_vt_not_complex<T3__>,
                              stan::is_stan_scalar<T4__>,
                              stan::is_col_vector<T5__>,
                              stan::is_vt_not_complex<T5__>>*>
Eigen::Matrix<stan::promote_args_t<T1__, stan::base_type_t<T2__>,
                stan::base_type_t<T3__>, T4__, stan::base_type_t<T5__>>,1,-1>
weights_regimes(const int& n_reg, const T1__& a, const T2__&
                t_beginning_arg__, const T3__& t_end_arg__, const T4__& time,
                const T5__& reg_match_arg__, const int& nodes, std::ostream*
                pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T1__,
                             stan::base_type_t<T2__>,
                             stan::base_type_t<T3__>, T4__,
                             stan::base_type_t<T5__>>;
  int current_statement__ = 0;
  const auto& t_beginning = stan::math::to_ref(t_beginning_arg__);
  const auto& t_end = stan::math::to_ref(t_end_arg__);
  const auto& reg_match = stan::math::to_ref(reg_match_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 143;
    stan::math::validate_non_negative_index("weight_seg", "nodes", nodes);
    Eigen::Matrix<local_scalar_t__,-1,1> weight_seg =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nodes, DUMMY_VAR__);
    current_statement__ = 144;
    stan::model::assign(weight_seg,
      weight_segments(a,
        stan::model::rvalue(t_beginning, "t_beginning",
          stan::model::index_min_max(1, (nodes - 1))),
        stan::model::rvalue(t_end, "t_end",
          stan::model::index_min_max(1, (nodes - 1))), time, nodes, pstream__),
      "assigning variable weight_seg");
    current_statement__ = 145;
    stan::math::validate_non_negative_index("reg_weights", "n_reg", n_reg);
    Eigen::Matrix<local_scalar_t__,-1,1> reg_weights =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_reg, DUMMY_VAR__);
    current_statement__ = 146;
    stan::model::assign(reg_weights, stan::math::rep_vector(0, n_reg),
      "assigning variable reg_weights");
    current_statement__ = 151;
    for (int i = 1; i <= n_reg; ++i) {
      current_statement__ = 147;
      stan::math::validate_non_negative_index("ids",
        "num_matches(reg_match, i)",
        num_matches(reg_match, static_cast<double>(i), pstream__));
      std::vector<int> ids =
        std::vector<int>(num_matches(reg_match, static_cast<double>(i),
                           pstream__), std::numeric_limits<int>::min());
      current_statement__ = 148;
      stan::model::assign(ids,
        which_equal(reg_match, static_cast<double>(i), pstream__),
        "assigning variable ids");
      current_statement__ = 149;
      stan::model::assign(reg_weights,
        stan::math::sum(
          stan::model::rvalue(weight_seg, "weight_seg",
            stan::model::index_multi(ids))),
        "assigning variable reg_weights", stan::model::index_uni(i));
    }
    current_statement__ = 152;
    return stan::math::transpose(reg_weights);
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T2__, typename T3__, typename T4__, typename T5__,
          typename T6__,
          stan::require_all_t<stan::is_stan_scalar<T2__>,
                              stan::is_eigen_matrix_dynamic<T3__>,
                              stan::is_vt_not_complex<T3__>,
                              stan::is_eigen_matrix_dynamic<T4__>,
                              stan::is_vt_not_complex<T4__>,
                              stan::is_eigen_matrix_dynamic<T5__>,
                              stan::is_vt_not_complex<T5__>,
                              stan::is_eigen_matrix_dynamic<T6__>,
                              stan::is_vt_not_complex<T6__>>*>
Eigen::Matrix<stan::promote_args_t<T2__, stan::base_type_t<T3__>,
                stan::base_type_t<T4__>, stan::base_type_t<T5__>,
                stan::base_type_t<T6__>>,-1,-1>
calc_optima_matrix(const int& N, const int& n_reg, const T2__& a, const T3__&
                   t_beginning_arg__, const T4__& t_end_arg__, const T5__&
                   times_arg__, const T6__& reg_match_arg__,
                   const std::vector<int>& nodes, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T2__,
                             stan::base_type_t<T3__>,
                             stan::base_type_t<T4__>,
                             stan::base_type_t<T5__>,
                             stan::base_type_t<T6__>>;
  int current_statement__ = 0;
  const auto& t_beginning = stan::math::to_ref(t_beginning_arg__);
  const auto& t_end = stan::math::to_ref(t_end_arg__);
  const auto& times = stan::math::to_ref(times_arg__);
  const auto& reg_match = stan::math::to_ref(reg_match_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 154;
    stan::math::validate_non_negative_index("optima_matrix", "N", N);
    current_statement__ = 155;
    stan::math::validate_non_negative_index("optima_matrix", "n_reg", n_reg);
    Eigen::Matrix<local_scalar_t__,-1,-1> optima_matrix =
      Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N, n_reg, DUMMY_VAR__);
    current_statement__ = 156;
    stan::model::assign(optima_matrix, stan::math::rep_matrix(0, N, n_reg),
      "assigning variable optima_matrix");
    current_statement__ = 159;
    for (int i = 1; i <= N; ++i) {
      current_statement__ = 157;
      stan::model::assign(optima_matrix,
        weights_regimes(n_reg, a,
          stan::math::transpose(
            stan::model::rvalue(t_beginning, "t_beginning",
              stan::model::index_uni(i), stan::model::index_omni())),
          stan::math::transpose(
            stan::model::rvalue(t_end, "t_end", stan::model::index_uni(i),
              stan::model::index_omni())),
          stan::model::rvalue(times, "times", stan::model::index_uni(i),
            stan::model::index_uni(1)),
          stan::math::transpose(
            stan::model::rvalue(reg_match, "reg_match",
              stan::model::index_uni(i), stan::model::index_omni())),
          stan::model::rvalue(nodes, "nodes", stan::model::index_uni(i)),
          pstream__), "assigning variable optima_matrix",
        stan::model::index_uni(i), stan::model::index_omni());
    }
    current_statement__ = 160;
    return optima_matrix;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_eigen_matrix_dynamic<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              stan::is_eigen_matrix_dynamic<T3__>,
                              stan::is_vt_not_complex<T3__>>*>
Eigen::Matrix<stan::promote_args_t<T0__, T1__, stan::base_type_t<T2__>,
                stan::base_type_t<T3__>>,-1,-1>
calc_direct_V(const T0__& a, const T1__& sigma2_y, const T2__& ta_arg__,
              const T3__& tij_arg__, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__,
                             stan::base_type_t<T2__>,
                             stan::base_type_t<T3__>>;
  int current_statement__ = 0;
  const auto& ta = stan::math::to_ref(ta_arg__);
  const auto& tij = stan::math::to_ref(tij_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int N = std::numeric_limits<int>::min();
    current_statement__ = 162;
    N = stan::model::rvalue(stan::math::dims(ta), "dims(ta)",
          stan::model::index_uni(1));
    current_statement__ = 163;
    stan::math::validate_non_negative_index("Vt", "N", N);
    current_statement__ = 164;
    stan::math::validate_non_negative_index("Vt", "N", N);
    Eigen::Matrix<local_scalar_t__,-1,-1> Vt =
      Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N, N, DUMMY_VAR__);
    current_statement__ = 166;
    stan::model::assign(Vt,
      stan::math::multiply((sigma2_y / (2 * a)),
        stan::math::elt_multiply(
          stan::math::subtract(1,
            stan::math::exp(stan::math::multiply((-2 * a), ta))),
          stan::math::exp(stan::math::multiply(-a, tij)))),
      "assigning variable Vt");
    current_statement__ = 167;
    return Vt;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
#include <stan_meta_header.hpp>
class model_blouchOU_reg_direct_ve final : public model_base_crtp<model_blouchOU_reg_direct_ve> {
private:
  int N;
  int n_reg;
  int Z_direct;
  int Z_X_error;
  int max_node_num;
  Eigen::Matrix<double,-1,1> Y_obs_data__;
  Eigen::Matrix<double,-1,-1> X_obs_data__;
  Eigen::Matrix<double,-1,1> Y_error_data__;
  Eigen::Matrix<double,-1,-1> X_error_data__;
  Eigen::Matrix<double,-1,-1> ta_data__;
  Eigen::Matrix<double,-1,-1> tij_data__;
  Eigen::Matrix<double,-1,-1> tja_data__;
  Eigen::Matrix<double,-1,1> T_term_data__;
  Eigen::Matrix<double,-1,-1> t_beginning_data__;
  Eigen::Matrix<double,-1,-1> t_end_data__;
  Eigen::Matrix<double,-1,-1> times_data__;
  Eigen::Matrix<double,-1,-1> reg_match_data__;
  std::vector<int> nodes;
  std::vector<int> reg_tips;
  Eigen::Matrix<double,-1,1> hl_prior_data__;
  double vy_prior;
  Eigen::Matrix<double,-1,1> optima_prior_data__;
  Eigen::Matrix<double,-1,1> beta_prior_data__;
  Eigen::Map<Eigen::Matrix<double,-1,1>> Y_obs{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X_obs{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> Y_error{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X_error{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> ta{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> tij{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> tja{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> T_term{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> t_beginning{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> t_end{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> times{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> reg_match{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> hl_prior{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> optima_prior{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> beta_prior{nullptr, 0};
public:
  ~model_blouchOU_reg_direct_ve() {}
  model_blouchOU_reg_direct_ve(stan::io::var_context& context__, unsigned int
                               random_seed__ = 0, std::ostream*
                               pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_blouchOU_reg_direct_ve_namespace::model_blouchOU_reg_direct_ve";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 62;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 62;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 63;
      context__.validate_dims("data initialization", "n_reg", "int",
        std::vector<size_t>{});
      n_reg = std::numeric_limits<int>::min();
      current_statement__ = 63;
      n_reg = context__.vals_i("n_reg")[(1 - 1)];
      current_statement__ = 64;
      context__.validate_dims("data initialization", "Z_direct", "int",
        std::vector<size_t>{});
      Z_direct = std::numeric_limits<int>::min();
      current_statement__ = 64;
      Z_direct = context__.vals_i("Z_direct")[(1 - 1)];
      current_statement__ = 65;
      context__.validate_dims("data initialization", "Z_X_error", "int",
        std::vector<size_t>{});
      Z_X_error = std::numeric_limits<int>::min();
      current_statement__ = 65;
      Z_X_error = context__.vals_i("Z_X_error")[(1 - 1)];
      current_statement__ = 66;
      context__.validate_dims("data initialization", "max_node_num", "int",
        std::vector<size_t>{});
      max_node_num = std::numeric_limits<int>::min();
      current_statement__ = 66;
      max_node_num = context__.vals_i("max_node_num")[(1 - 1)];
      current_statement__ = 67;
      stan::math::validate_non_negative_index("Y_obs", "N", N);
      current_statement__ = 68;
      context__.validate_dims("data initialization", "Y_obs", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      Y_obs_data__ = Eigen::Matrix<double,-1,1>::Constant(N,
                       std::numeric_limits<double>::quiet_NaN());
      new (&Y_obs)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(Y_obs_data__.data(), N);
      {
        std::vector<local_scalar_t__> Y_obs_flat__;
        current_statement__ = 68;
        Y_obs_flat__ = context__.vals_r("Y_obs");
        current_statement__ = 68;
        pos__ = 1;
        current_statement__ = 68;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 68;
          stan::model::assign(Y_obs, Y_obs_flat__[(pos__ - 1)],
            "assigning variable Y_obs", stan::model::index_uni(sym1__));
          current_statement__ = 68;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 69;
      stan::math::validate_non_negative_index("X_obs", "N", N);
      current_statement__ = 70;
      stan::math::validate_non_negative_index("X_obs", "Z_direct", Z_direct);
      current_statement__ = 71;
      context__.validate_dims("data initialization", "X_obs", "double",
        std::vector<size_t>{static_cast<size_t>(N),
          static_cast<size_t>(Z_direct)});
      X_obs_data__ = Eigen::Matrix<double,-1,-1>::Constant(N, Z_direct,
                       std::numeric_limits<double>::quiet_NaN());
      new (&X_obs)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(X_obs_data__.data(), N,
        Z_direct);
      {
        std::vector<local_scalar_t__> X_obs_flat__;
        current_statement__ = 71;
        X_obs_flat__ = context__.vals_r("X_obs");
        current_statement__ = 71;
        pos__ = 1;
        current_statement__ = 71;
        for (int sym1__ = 1; sym1__ <= Z_direct; ++sym1__) {
          current_statement__ = 71;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 71;
            stan::model::assign(X_obs, X_obs_flat__[(pos__ - 1)],
              "assigning variable X_obs", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 71;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 72;
      stan::math::validate_non_negative_index("Y_error", "N", N);
      current_statement__ = 73;
      context__.validate_dims("data initialization", "Y_error", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      Y_error_data__ = Eigen::Matrix<double,-1,1>::Constant(N,
                         std::numeric_limits<double>::quiet_NaN());
      new (&Y_error)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(Y_error_data__.data(), N);
      {
        std::vector<local_scalar_t__> Y_error_flat__;
        current_statement__ = 73;
        Y_error_flat__ = context__.vals_r("Y_error");
        current_statement__ = 73;
        pos__ = 1;
        current_statement__ = 73;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 73;
          stan::model::assign(Y_error, Y_error_flat__[(pos__ - 1)],
            "assigning variable Y_error", stan::model::index_uni(sym1__));
          current_statement__ = 73;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 74;
      stan::math::validate_non_negative_index("X_error", "N", N);
      current_statement__ = 75;
      stan::math::validate_non_negative_index("X_error", "Z_X_error",
        Z_X_error);
      current_statement__ = 76;
      context__.validate_dims("data initialization", "X_error", "double",
        std::vector<size_t>{static_cast<size_t>(N),
          static_cast<size_t>(Z_X_error)});
      X_error_data__ = Eigen::Matrix<double,-1,-1>::Constant(N, Z_X_error,
                         std::numeric_limits<double>::quiet_NaN());
      new (&X_error)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(X_error_data__.data(), N,
        Z_X_error);
      {
        std::vector<local_scalar_t__> X_error_flat__;
        current_statement__ = 76;
        X_error_flat__ = context__.vals_r("X_error");
        current_statement__ = 76;
        pos__ = 1;
        current_statement__ = 76;
        for (int sym1__ = 1; sym1__ <= Z_X_error; ++sym1__) {
          current_statement__ = 76;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 76;
            stan::model::assign(X_error, X_error_flat__[(pos__ - 1)],
              "assigning variable X_error", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 76;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 77;
      stan::math::validate_non_negative_index("ta", "N", N);
      current_statement__ = 78;
      stan::math::validate_non_negative_index("ta", "N", N);
      current_statement__ = 79;
      context__.validate_dims("data initialization", "ta", "double",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(N)});
      ta_data__ = Eigen::Matrix<double,-1,-1>::Constant(N, N,
                    std::numeric_limits<double>::quiet_NaN());
      new (&ta) Eigen::Map<Eigen::Matrix<double,-1,-1>>(ta_data__.data(), N,
        N);
      {
        std::vector<local_scalar_t__> ta_flat__;
        current_statement__ = 79;
        ta_flat__ = context__.vals_r("ta");
        current_statement__ = 79;
        pos__ = 1;
        current_statement__ = 79;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 79;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 79;
            stan::model::assign(ta, ta_flat__[(pos__ - 1)],
              "assigning variable ta", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 79;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 80;
      stan::math::validate_non_negative_index("tij", "N", N);
      current_statement__ = 81;
      stan::math::validate_non_negative_index("tij", "N", N);
      current_statement__ = 82;
      context__.validate_dims("data initialization", "tij", "double",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(N)});
      tij_data__ = Eigen::Matrix<double,-1,-1>::Constant(N, N,
                     std::numeric_limits<double>::quiet_NaN());
      new (&tij) Eigen::Map<Eigen::Matrix<double,-1,-1>>(tij_data__.data(),
        N, N);
      {
        std::vector<local_scalar_t__> tij_flat__;
        current_statement__ = 82;
        tij_flat__ = context__.vals_r("tij");
        current_statement__ = 82;
        pos__ = 1;
        current_statement__ = 82;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 82;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 82;
            stan::model::assign(tij, tij_flat__[(pos__ - 1)],
              "assigning variable tij", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 82;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 83;
      stan::math::validate_non_negative_index("tja", "N", N);
      current_statement__ = 84;
      stan::math::validate_non_negative_index("tja", "N", N);
      current_statement__ = 85;
      context__.validate_dims("data initialization", "tja", "double",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(N)});
      tja_data__ = Eigen::Matrix<double,-1,-1>::Constant(N, N,
                     std::numeric_limits<double>::quiet_NaN());
      new (&tja) Eigen::Map<Eigen::Matrix<double,-1,-1>>(tja_data__.data(),
        N, N);
      {
        std::vector<local_scalar_t__> tja_flat__;
        current_statement__ = 85;
        tja_flat__ = context__.vals_r("tja");
        current_statement__ = 85;
        pos__ = 1;
        current_statement__ = 85;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 85;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 85;
            stan::model::assign(tja, tja_flat__[(pos__ - 1)],
              "assigning variable tja", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 85;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 86;
      stan::math::validate_non_negative_index("T_term", "N", N);
      current_statement__ = 87;
      context__.validate_dims("data initialization", "T_term", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      T_term_data__ = Eigen::Matrix<double,-1,1>::Constant(N,
                        std::numeric_limits<double>::quiet_NaN());
      new (&T_term)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(T_term_data__.data(), N);
      {
        std::vector<local_scalar_t__> T_term_flat__;
        current_statement__ = 87;
        T_term_flat__ = context__.vals_r("T_term");
        current_statement__ = 87;
        pos__ = 1;
        current_statement__ = 87;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 87;
          stan::model::assign(T_term, T_term_flat__[(pos__ - 1)],
            "assigning variable T_term", stan::model::index_uni(sym1__));
          current_statement__ = 87;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 88;
      stan::math::validate_non_negative_index("t_beginning", "N", N);
      current_statement__ = 89;
      stan::math::validate_non_negative_index("t_beginning", "max_node_num",
        max_node_num);
      current_statement__ = 90;
      context__.validate_dims("data initialization", "t_beginning", "double",
        std::vector<size_t>{static_cast<size_t>(N),
          static_cast<size_t>(max_node_num)});
      t_beginning_data__ = Eigen::Matrix<double,-1,-1>::Constant(N,
                             max_node_num,
                             std::numeric_limits<double>::quiet_NaN());
      new (&t_beginning)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(t_beginning_data__.data(), N,
        max_node_num);
      {
        std::vector<local_scalar_t__> t_beginning_flat__;
        current_statement__ = 90;
        t_beginning_flat__ = context__.vals_r("t_beginning");
        current_statement__ = 90;
        pos__ = 1;
        current_statement__ = 90;
        for (int sym1__ = 1; sym1__ <= max_node_num; ++sym1__) {
          current_statement__ = 90;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 90;
            stan::model::assign(t_beginning, t_beginning_flat__[(pos__ - 1)],
              "assigning variable t_beginning",
              stan::model::index_uni(sym2__), stan::model::index_uni(sym1__));
            current_statement__ = 90;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 91;
      stan::math::validate_non_negative_index("t_end", "N", N);
      current_statement__ = 92;
      stan::math::validate_non_negative_index("t_end", "max_node_num",
        max_node_num);
      current_statement__ = 93;
      context__.validate_dims("data initialization", "t_end", "double",
        std::vector<size_t>{static_cast<size_t>(N),
          static_cast<size_t>(max_node_num)});
      t_end_data__ = Eigen::Matrix<double,-1,-1>::Constant(N, max_node_num,
                       std::numeric_limits<double>::quiet_NaN());
      new (&t_end)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(t_end_data__.data(), N,
        max_node_num);
      {
        std::vector<local_scalar_t__> t_end_flat__;
        current_statement__ = 93;
        t_end_flat__ = context__.vals_r("t_end");
        current_statement__ = 93;
        pos__ = 1;
        current_statement__ = 93;
        for (int sym1__ = 1; sym1__ <= max_node_num; ++sym1__) {
          current_statement__ = 93;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 93;
            stan::model::assign(t_end, t_end_flat__[(pos__ - 1)],
              "assigning variable t_end", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 93;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 94;
      stan::math::validate_non_negative_index("times", "N", N);
      current_statement__ = 95;
      stan::math::validate_non_negative_index("times", "max_node_num",
        max_node_num);
      current_statement__ = 96;
      context__.validate_dims("data initialization", "times", "double",
        std::vector<size_t>{static_cast<size_t>(N),
          static_cast<size_t>(max_node_num)});
      times_data__ = Eigen::Matrix<double,-1,-1>::Constant(N, max_node_num,
                       std::numeric_limits<double>::quiet_NaN());
      new (&times)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(times_data__.data(), N,
        max_node_num);
      {
        std::vector<local_scalar_t__> times_flat__;
        current_statement__ = 96;
        times_flat__ = context__.vals_r("times");
        current_statement__ = 96;
        pos__ = 1;
        current_statement__ = 96;
        for (int sym1__ = 1; sym1__ <= max_node_num; ++sym1__) {
          current_statement__ = 96;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 96;
            stan::model::assign(times, times_flat__[(pos__ - 1)],
              "assigning variable times", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 96;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 97;
      stan::math::validate_non_negative_index("reg_match", "N", N);
      current_statement__ = 98;
      stan::math::validate_non_negative_index("reg_match", "max_node_num",
        max_node_num);
      current_statement__ = 99;
      context__.validate_dims("data initialization", "reg_match", "double",
        std::vector<size_t>{static_cast<size_t>(N),
          static_cast<size_t>(max_node_num)});
      reg_match_data__ = Eigen::Matrix<double,-1,-1>::Constant(N,
                           max_node_num,
                           std::numeric_limits<double>::quiet_NaN());
      new (&reg_match)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(reg_match_data__.data(), N,
        max_node_num);
      {
        std::vector<local_scalar_t__> reg_match_flat__;
        current_statement__ = 99;
        reg_match_flat__ = context__.vals_r("reg_match");
        current_statement__ = 99;
        pos__ = 1;
        current_statement__ = 99;
        for (int sym1__ = 1; sym1__ <= max_node_num; ++sym1__) {
          current_statement__ = 99;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 99;
            stan::model::assign(reg_match, reg_match_flat__[(pos__ - 1)],
              "assigning variable reg_match", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 99;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 100;
      stan::math::validate_non_negative_index("nodes", "N", N);
      current_statement__ = 101;
      context__.validate_dims("data initialization", "nodes", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      nodes = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 101;
      nodes = context__.vals_i("nodes");
      current_statement__ = 102;
      stan::math::validate_non_negative_index("reg_tips", "N", N);
      current_statement__ = 103;
      context__.validate_dims("data initialization", "reg_tips", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      reg_tips = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 103;
      reg_tips = context__.vals_i("reg_tips");
      current_statement__ = 104;
      context__.validate_dims("data initialization", "hl_prior", "double",
        std::vector<size_t>{static_cast<size_t>(2)});
      hl_prior_data__ = Eigen::Matrix<double,-1,1>::Constant(2,
                          std::numeric_limits<double>::quiet_NaN());
      new (&hl_prior)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(hl_prior_data__.data(), 2);
      {
        std::vector<local_scalar_t__> hl_prior_flat__;
        current_statement__ = 104;
        hl_prior_flat__ = context__.vals_r("hl_prior");
        current_statement__ = 104;
        pos__ = 1;
        current_statement__ = 104;
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          current_statement__ = 104;
          stan::model::assign(hl_prior, hl_prior_flat__[(pos__ - 1)],
            "assigning variable hl_prior", stan::model::index_uni(sym1__));
          current_statement__ = 104;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 105;
      context__.validate_dims("data initialization", "vy_prior", "double",
        std::vector<size_t>{});
      vy_prior = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 105;
      vy_prior = context__.vals_r("vy_prior")[(1 - 1)];
      current_statement__ = 106;
      context__.validate_dims("data initialization", "optima_prior",
        "double", std::vector<size_t>{static_cast<size_t>(2)});
      optima_prior_data__ = Eigen::Matrix<double,-1,1>::Constant(2,
                              std::numeric_limits<double>::quiet_NaN());
      new (&optima_prior)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(optima_prior_data__.data(), 2);
      {
        std::vector<local_scalar_t__> optima_prior_flat__;
        current_statement__ = 106;
        optima_prior_flat__ = context__.vals_r("optima_prior");
        current_statement__ = 106;
        pos__ = 1;
        current_statement__ = 106;
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          current_statement__ = 106;
          stan::model::assign(optima_prior, optima_prior_flat__[(pos__ - 1)],
            "assigning variable optima_prior", stan::model::index_uni(sym1__));
          current_statement__ = 106;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 107;
      context__.validate_dims("data initialization", "beta_prior", "double",
        std::vector<size_t>{static_cast<size_t>(2)});
      beta_prior_data__ = Eigen::Matrix<double,-1,1>::Constant(2,
                            std::numeric_limits<double>::quiet_NaN());
      new (&beta_prior)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(beta_prior_data__.data(), 2);
      {
        std::vector<local_scalar_t__> beta_prior_flat__;
        current_statement__ = 107;
        beta_prior_flat__ = context__.vals_r("beta_prior");
        current_statement__ = 107;
        pos__ = 1;
        current_statement__ = 107;
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          current_statement__ = 107;
          stan::model::assign(beta_prior, beta_prior_flat__[(pos__ - 1)],
            "assigning variable beta_prior", stan::model::index_uni(sym1__));
          current_statement__ = 107;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 108;
      stan::math::validate_non_negative_index("beta", "n_reg", n_reg);
      current_statement__ = 109;
      stan::math::validate_non_negative_index("beta", "Z_direct", Z_direct);
      current_statement__ = 110;
      stan::math::validate_non_negative_index("Y", "N", N);
      current_statement__ = 111;
      stan::math::validate_non_negative_index("X", "N", N);
      current_statement__ = 112;
      stan::math::validate_non_negative_index("X", "Z_direct", Z_direct);
      current_statement__ = 113;
      stan::math::validate_non_negative_index("optima", "n_reg", n_reg);
      current_statement__ = 114;
      stan::math::validate_non_negative_index("V", "N", N);
      current_statement__ = 115;
      stan::math::validate_non_negative_index("V", "N", N);
      current_statement__ = 116;
      stan::math::validate_non_negative_index("inv_V", "N", N);
      current_statement__ = 117;
      stan::math::validate_non_negative_index("inv_V", "N", N);
      current_statement__ = 118;
      stan::math::validate_non_negative_index("optima_matrix", "N", N);
      current_statement__ = 119;
      stan::math::validate_non_negative_index("optima_matrix", "n_reg", n_reg);
      current_statement__ = 120;
      stan::math::validate_non_negative_index("mu", "N", N);
      current_statement__ = 121;
      stan::math::validate_non_negative_index("log_lik", "N", N);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1 + (n_reg * Z_direct) + N + (N * Z_direct) + n_reg;
  }
  inline std::string model_name() const final {
    return "model_blouchOU_reg_direct_ve";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_blouchOU_reg_direct_ve_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ hl = DUMMY_VAR__;
      current_statement__ = 1;
      hl = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
             lp__);
      local_scalar_t__ vy = DUMMY_VAR__;
      current_statement__ = 2;
      vy = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
             lp__);
      Eigen::Matrix<local_scalar_t__,-1,-1> beta =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(n_reg, Z_direct,
          DUMMY_VAR__);
      current_statement__ = 3;
      beta = in__.template read<Eigen::Matrix<local_scalar_t__,-1,-1>>(n_reg,
               Z_direct);
      Eigen::Matrix<local_scalar_t__,-1,1> Y =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      current_statement__ = 4;
      Y = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(N);
      Eigen::Matrix<local_scalar_t__,-1,-1> X =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N, Z_direct,
          DUMMY_VAR__);
      current_statement__ = 5;
      X = in__.template read<Eigen::Matrix<local_scalar_t__,-1,-1>>(N,
            Z_direct);
      Eigen::Matrix<local_scalar_t__,-1,1> optima =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_reg, DUMMY_VAR__);
      current_statement__ = 6;
      optima = in__.template read<
                 Eigen::Matrix<local_scalar_t__,-1,1>>(n_reg);
      {
        current_statement__ = 31;
        stan::math::validate_non_negative_index("V", "N", N);
        current_statement__ = 32;
        stan::math::validate_non_negative_index("V", "N", N);
        Eigen::Matrix<local_scalar_t__,-1,-1> V =
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N, N, DUMMY_VAR__);
        current_statement__ = 34;
        stan::math::validate_non_negative_index("mu", "N", N);
        Eigen::Matrix<local_scalar_t__,-1,1> mu =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
        current_statement__ = 36;
        stan::math::validate_non_negative_index("L_v", "N", N);
        current_statement__ = 37;
        stan::math::validate_non_negative_index("L_v", "N", N);
        Eigen::Matrix<local_scalar_t__,-1,-1> L_v =
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N, N, DUMMY_VAR__);
        local_scalar_t__ a = DUMMY_VAR__;
        current_statement__ = 39;
        a = (stan::math::log(2) / hl);
        local_scalar_t__ sigma2_y = DUMMY_VAR__;
        current_statement__ = 40;
        sigma2_y = (vy * (2 * (stan::math::log(2) / hl)));
        current_statement__ = 41;
        stan::math::validate_non_negative_index("optima_matrix", "N", N);
        current_statement__ = 42;
        stan::math::validate_non_negative_index("optima_matrix", "n_reg",
          n_reg);
        Eigen::Matrix<local_scalar_t__,-1,-1> optima_matrix =
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N, n_reg,
            DUMMY_VAR__);
        current_statement__ = 44;
        lp_accum__.add(stan::math::lognormal_lpdf<false>(hl,
                         stan::model::rvalue(hl_prior, "hl_prior",
                           stan::model::index_uni(1)),
                         stan::model::rvalue(hl_prior, "hl_prior",
                           stan::model::index_uni(2))));
        current_statement__ = 45;
        lp_accum__.add(stan::math::exponential_lpdf<false>(vy, vy_prior));
        current_statement__ = 46;
        lp_accum__.add(stan::math::normal_lpdf<false>(optima,
                         stan::model::rvalue(optima_prior, "optima_prior",
                           stan::model::index_uni(1)),
                         stan::model::rvalue(optima_prior, "optima_prior",
                           stan::model::index_uni(2))));
        current_statement__ = 49;
        for (int i = 1; i <= Z_direct; ++i) {
          current_statement__ = 47;
          lp_accum__.add(stan::math::normal_lpdf<false>(
                           stan::model::rvalue(beta, "beta",
                             stan::model::index_omni(),
                             stan::model::index_uni(i)),
                           stan::model::rvalue(beta_prior, "beta_prior",
                             stan::model::index_uni(1)),
                           stan::model::rvalue(beta_prior, "beta_prior",
                             stan::model::index_uni(2))));
        }
        current_statement__ = 53;
        for (int i = 1; i <= Z_direct; ++i) {
          current_statement__ = 50;
          lp_accum__.add(stan::math::normal_lpdf<false>(
                           stan::model::rvalue(X, "X",
                             stan::model::index_omni(),
                             stan::model::index_uni(i)), 0, 1));
          current_statement__ = 51;
          lp_accum__.add(stan::math::normal_lpdf<false>(
                           stan::model::rvalue(X_obs, "X_obs",
                             stan::model::index_omni(),
                             stan::model::index_uni(i)),
                           stan::model::rvalue(X, "X",
                             stan::model::index_omni(),
                             stan::model::index_uni(i)),
                           stan::model::rvalue(X_error, "X_error",
                             stan::model::index_omni(),
                             stan::model::index_uni(i))));
        }
        current_statement__ = 54;
        stan::model::assign(optima_matrix,
          calc_optima_matrix(N, n_reg, a, t_beginning, t_end, times,
            reg_match, nodes, pstream__), "assigning variable optima_matrix");
        current_statement__ = 55;
        stan::model::assign(V,
          calc_direct_V(a, sigma2_y, ta, tij, pstream__),
          "assigning variable V");
        current_statement__ = 56;
        stan::model::assign(L_v, stan::math::cholesky_decompose(V),
          "assigning variable L_v");
        current_statement__ = 59;
        for (int i = 1; i <= N; ++i) {
          current_statement__ = 57;
          stan::model::assign(mu,
            (stan::math::multiply(
               stan::model::rvalue(optima_matrix, "optima_matrix",
                 stan::model::index_uni(i), stan::model::index_omni()),
               optima) +
            stan::math::multiply(
              stan::model::rvalue(X, "X", stan::model::index_uni(i),
                stan::model::index_omni()),
              stan::math::transpose(
                stan::model::rvalue(beta, "beta",
                  stan::model::index_uni(
                    stan::model::rvalue(reg_tips, "reg_tips",
                      stan::model::index_uni(i))), stan::model::index_omni())))),
            "assigning variable mu", stan::model::index_uni(i));
        }
        current_statement__ = 60;
        lp_accum__.add(stan::math::multi_normal_cholesky_lpdf<false>(Y, mu,
                         L_v));
        current_statement__ = 61;
        lp_accum__.add(stan::math::normal_lpdf<false>(Y_obs, Y, Y_error));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_blouchOU_reg_direct_ve_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      double hl = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      hl = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
             lp__);
      double vy = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      vy = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
             lp__);
      Eigen::Matrix<double,-1,-1> beta =
        Eigen::Matrix<double,-1,-1>::Constant(n_reg, Z_direct,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 3;
      beta = in__.template read<Eigen::Matrix<local_scalar_t__,-1,-1>>(n_reg,
               Z_direct);
      Eigen::Matrix<double,-1,1> Y =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 4;
      Y = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(N);
      Eigen::Matrix<double,-1,-1> X =
        Eigen::Matrix<double,-1,-1>::Constant(N, Z_direct,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 5;
      X = in__.template read<Eigen::Matrix<local_scalar_t__,-1,-1>>(N,
            Z_direct);
      Eigen::Matrix<double,-1,1> optima =
        Eigen::Matrix<double,-1,1>::Constant(n_reg,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 6;
      optima = in__.template read<
                 Eigen::Matrix<local_scalar_t__,-1,1>>(n_reg);
      out__.write(hl);
      out__.write(vy);
      out__.write(beta);
      out__.write(Y);
      out__.write(X);
      out__.write(optima);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      Eigen::Matrix<double,-1,-1> V =
        Eigen::Matrix<double,-1,-1>::Constant(N, N,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,-1> inv_V =
        Eigen::Matrix<double,-1,-1>::Constant(N, N,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,-1> optima_matrix =
        Eigen::Matrix<double,-1,-1>::Constant(N, n_reg,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> mu =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      double g_i = std::numeric_limits<double>::quiet_NaN();
      double sigma_ii = std::numeric_limits<double>::quiet_NaN();
      double sigma_i = std::numeric_limits<double>::quiet_NaN();
      double u_i = std::numeric_limits<double>::quiet_NaN();
      Eigen::Matrix<double,-1,1> log_lik =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      double sigma2_y = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 16;
      sigma2_y = (vy * (2 * (stan::math::log(2) / hl)));
      double a = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 17;
      a = (stan::math::log(2) / hl);
      current_statement__ = 18;
      stan::model::assign(V, calc_direct_V(a, sigma2_y, ta, tij, pstream__),
        "assigning variable V");
      current_statement__ = 19;
      stan::model::assign(optima_matrix,
        calc_optima_matrix(N, n_reg, a, t_beginning, t_end, times, reg_match,
          nodes, pstream__), "assigning variable optima_matrix");
      current_statement__ = 20;
      stan::model::assign(inv_V, stan::math::inverse(V),
        "assigning variable inv_V");
      current_statement__ = 23;
      for (int i = 1; i <= N; ++i) {
        current_statement__ = 21;
        stan::model::assign(mu,
          (stan::math::multiply(
             stan::model::rvalue(optima_matrix, "optima_matrix",
               stan::model::index_uni(i), stan::model::index_omni()), optima)
          +
          stan::math::multiply(
            stan::model::rvalue(X, "X", stan::model::index_uni(i),
              stan::model::index_omni()),
            stan::math::transpose(
              stan::model::rvalue(beta, "beta",
                stan::model::index_uni(
                  stan::model::rvalue(reg_tips, "reg_tips",
                    stan::model::index_uni(i))), stan::model::index_omni())))),
          "assigning variable mu", stan::model::index_uni(i));
      }
      current_statement__ = 30;
      for (int i = 1; i <= N; ++i) {
        current_statement__ = 24;
        g_i = stan::model::rvalue(
                stan::math::multiply(inv_V, stan::math::subtract(Y, mu)),
                "(inv_V * (Y - mu))", stan::model::index_uni(i));
        current_statement__ = 25;
        sigma_ii = stan::model::rvalue(inv_V, "inv_V",
                     stan::model::index_uni(i), stan::model::index_uni(i));
        current_statement__ = 26;
        u_i = (stan::model::rvalue(Y, "Y", stan::model::index_uni(i)) - (g_i
          / sigma_ii));
        current_statement__ = 27;
        sigma_i = (1 / sigma_ii);
        current_statement__ = 28;
        stan::model::assign(log_lik, ((-0.5 *
          stan::math::log(((2 * stan::math::pi()) * sigma_i))) - (0.5 *
          (stan::math::square(
             (stan::model::rvalue(Y, "Y", stan::model::index_uni(i)) - u_i))
          / sigma_i))), "assigning variable log_lik",
          stan::model::index_uni(i));
      }
      out__.write(V);
      out__.write(inv_V);
      out__.write(optima_matrix);
      out__.write(mu);
      out__.write(g_i);
      out__.write(sigma_ii);
      out__.write(sigma_i);
      out__.write(u_i);
      out__.write(log_lik);
      out__.write(sigma2_y);
      out__.write(a);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ hl = DUMMY_VAR__;
      current_statement__ = 1;
      hl = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, hl);
      local_scalar_t__ vy = DUMMY_VAR__;
      current_statement__ = 2;
      vy = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, vy);
      Eigen::Matrix<local_scalar_t__,-1,-1> beta =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(n_reg, Z_direct,
          DUMMY_VAR__);
      current_statement__ = 3;
      stan::model::assign(beta,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,-1>>(n_reg, Z_direct),
        "assigning variable beta");
      out__.write(beta);
      Eigen::Matrix<local_scalar_t__,-1,1> Y =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      current_statement__ = 4;
      stan::model::assign(Y,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(N),
        "assigning variable Y");
      out__.write(Y);
      Eigen::Matrix<local_scalar_t__,-1,-1> X =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N, Z_direct,
          DUMMY_VAR__);
      current_statement__ = 5;
      stan::model::assign(X,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,-1>>(N, Z_direct),
        "assigning variable X");
      out__.write(X);
      Eigen::Matrix<local_scalar_t__,-1,1> optima =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_reg, DUMMY_VAR__);
      current_statement__ = 6;
      stan::model::assign(optima,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(n_reg),
        "assigning variable optima");
      out__.write(optima);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "hl", "double",
        std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "vy", "double",
        std::vector<size_t>{});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "beta", "double",
        std::vector<size_t>{static_cast<size_t>(n_reg),
          static_cast<size_t>(Z_direct)});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "Y", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization", "X", "double",
        std::vector<size_t>{static_cast<size_t>(N),
          static_cast<size_t>(Z_direct)});
      current_statement__ = 6;
      context__.validate_dims("parameter initialization", "optima", "double",
        std::vector<size_t>{static_cast<size_t>(n_reg)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ hl = DUMMY_VAR__;
      current_statement__ = 1;
      hl = context__.vals_r("hl")[(1 - 1)];
      out__.write_free_lb(0, hl);
      local_scalar_t__ vy = DUMMY_VAR__;
      current_statement__ = 2;
      vy = context__.vals_r("vy")[(1 - 1)];
      out__.write_free_lb(0, vy);
      Eigen::Matrix<local_scalar_t__,-1,-1> beta =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(n_reg, Z_direct,
          DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> beta_flat__;
        current_statement__ = 3;
        beta_flat__ = context__.vals_r("beta");
        current_statement__ = 3;
        pos__ = 1;
        current_statement__ = 3;
        for (int sym1__ = 1; sym1__ <= Z_direct; ++sym1__) {
          current_statement__ = 3;
          for (int sym2__ = 1; sym2__ <= n_reg; ++sym2__) {
            current_statement__ = 3;
            stan::model::assign(beta, beta_flat__[(pos__ - 1)],
              "assigning variable beta", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 3;
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write(beta);
      Eigen::Matrix<local_scalar_t__,-1,1> Y =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> Y_flat__;
        current_statement__ = 4;
        Y_flat__ = context__.vals_r("Y");
        current_statement__ = 4;
        pos__ = 1;
        current_statement__ = 4;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 4;
          stan::model::assign(Y, Y_flat__[(pos__ - 1)],
            "assigning variable Y", stan::model::index_uni(sym1__));
          current_statement__ = 4;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(Y);
      Eigen::Matrix<local_scalar_t__,-1,-1> X =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N, Z_direct,
          DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> X_flat__;
        current_statement__ = 5;
        X_flat__ = context__.vals_r("X");
        current_statement__ = 5;
        pos__ = 1;
        current_statement__ = 5;
        for (int sym1__ = 1; sym1__ <= Z_direct; ++sym1__) {
          current_statement__ = 5;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 5;
            stan::model::assign(X, X_flat__[(pos__ - 1)],
              "assigning variable X", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 5;
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write(X);
      Eigen::Matrix<local_scalar_t__,-1,1> optima =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_reg, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> optima_flat__;
        current_statement__ = 6;
        optima_flat__ = context__.vals_r("optima");
        current_statement__ = 6;
        pos__ = 1;
        current_statement__ = 6;
        for (int sym1__ = 1; sym1__ <= n_reg; ++sym1__) {
          current_statement__ = 6;
          stan::model::assign(optima, optima_flat__[(pos__ - 1)],
            "assigning variable optima", stan::model::index_uni(sym1__));
          current_statement__ = 6;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(optima);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"hl", "vy", "beta", "Y", "X",
                "optima"};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      std::vector<std::string>
        temp{"V", "inv_V", "optima_matrix", "mu", "g_i", "sigma_ii",
             "sigma_i", "u_i", "log_lik", "sigma2_y", "a"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(n_reg),
                  static_cast<size_t>(Z_direct)},
                std::vector<size_t>{static_cast<size_t>(N)},
                std::vector<size_t>{static_cast<size_t>(N),
                  static_cast<size_t>(Z_direct)},
                std::vector<size_t>{static_cast<size_t>(n_reg)}};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(N),
               static_cast<size_t>(N)},
             std::vector<size_t>{static_cast<size_t>(N),
               static_cast<size_t>(N)},
             std::vector<size_t>{static_cast<size_t>(N),
               static_cast<size_t>(n_reg)},
             std::vector<size_t>{static_cast<size_t>(N)},
             std::vector<size_t>{}, std::vector<size_t>{},
             std::vector<size_t>{}, std::vector<size_t>{},
             std::vector<size_t>{static_cast<size_t>(N)},
             std::vector<size_t>{}, std::vector<size_t>{}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "hl");
    param_names__.emplace_back(std::string() + "vy");
    for (int sym1__ = 1; sym1__ <= Z_direct; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= n_reg; ++sym2__) {
        param_names__.emplace_back(std::string() + "beta" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
      param_names__.emplace_back(std::string() + "Y" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= Z_direct; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
        param_names__.emplace_back(std::string() + "X" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= n_reg; ++sym1__) {
      param_names__.emplace_back(std::string() + "optima" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          param_names__.emplace_back(std::string() + "V" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          param_names__.emplace_back(std::string() + "inv_V" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= n_reg; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          param_names__.emplace_back(std::string() + "optima_matrix" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "mu" + '.' +
          std::to_string(sym1__));
      }
      param_names__.emplace_back(std::string() + "g_i");
      param_names__.emplace_back(std::string() + "sigma_ii");
      param_names__.emplace_back(std::string() + "sigma_i");
      param_names__.emplace_back(std::string() + "u_i");
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_lik" + '.' +
          std::to_string(sym1__));
      }
      param_names__.emplace_back(std::string() + "sigma2_y");
      param_names__.emplace_back(std::string() + "a");
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "hl");
    param_names__.emplace_back(std::string() + "vy");
    for (int sym1__ = 1; sym1__ <= Z_direct; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= n_reg; ++sym2__) {
        param_names__.emplace_back(std::string() + "beta" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
      param_names__.emplace_back(std::string() + "Y" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= Z_direct; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
        param_names__.emplace_back(std::string() + "X" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= n_reg; ++sym1__) {
      param_names__.emplace_back(std::string() + "optima" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          param_names__.emplace_back(std::string() + "V" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          param_names__.emplace_back(std::string() + "inv_V" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= n_reg; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          param_names__.emplace_back(std::string() + "optima_matrix" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "mu" + '.' +
          std::to_string(sym1__));
      }
      param_names__.emplace_back(std::string() + "g_i");
      param_names__.emplace_back(std::string() + "sigma_ii");
      param_names__.emplace_back(std::string() + "sigma_i");
      param_names__.emplace_back(std::string() + "u_i");
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_lik" + '.' +
          std::to_string(sym1__));
      }
      param_names__.emplace_back(std::string() + "sigma2_y");
      param_names__.emplace_back(std::string() + "a");
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"hl\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"vy\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(n_reg) + ",\"cols\":" + std::to_string(Z_direct) + "},\"block\":\"parameters\"},{\"name\":\"Y\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"parameters\"},{\"name\":\"X\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(N) + ",\"cols\":" + std::to_string(Z_direct) + "},\"block\":\"parameters\"},{\"name\":\"optima\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n_reg) + "},\"block\":\"parameters\"},{\"name\":\"V\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(N) + ",\"cols\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"},{\"name\":\"inv_V\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(N) + ",\"cols\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"},{\"name\":\"optima_matrix\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(N) + ",\"cols\":" + std::to_string(n_reg) + "},\"block\":\"generated_quantities\"},{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"},{\"name\":\"g_i\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"sigma_ii\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"sigma_i\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"u_i\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"},{\"name\":\"sigma2_y\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"a\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"hl\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"vy\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(n_reg) + ",\"cols\":" + std::to_string(Z_direct) + "},\"block\":\"parameters\"},{\"name\":\"Y\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"parameters\"},{\"name\":\"X\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(N) + ",\"cols\":" + std::to_string(Z_direct) + "},\"block\":\"parameters\"},{\"name\":\"optima\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n_reg) + "},\"block\":\"parameters\"},{\"name\":\"V\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(N) + ",\"cols\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"},{\"name\":\"inv_V\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(N) + ",\"cols\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"},{\"name\":\"optima_matrix\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(N) + ",\"cols\":" + std::to_string(n_reg) + "},\"block\":\"generated_quantities\"},{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"},{\"name\":\"g_i\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"sigma_ii\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"sigma_i\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"u_i\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"},{\"name\":\"sigma2_y\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"a\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((((1 + 1) + (n_reg * Z_direct)) + N) + (N *
      Z_direct)) + n_reg);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities *
      ((((((((((((N * N) + (N * N)) + (N * n_reg)) + N) + 1) + 1) + 1) + 1) +
      N) + 1) + 1));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((((1 + 1) + (n_reg * Z_direct)) + N) + (N *
      Z_direct)) + n_reg);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities *
      ((((((((((((N * N) + (N * N)) + (N * n_reg)) + N) + 1) + 1) + 1) + 1) +
      N) + 1) + 1));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_blouchOU_reg_direct_ve_namespace::model_blouchOU_reg_direct_ve;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_blouchOU_reg_direct_ve_namespace::profiles__;
}
#endif
#endif
