# Generated by rstantools.  Do not edit by hand.

# names of stan models
stanmodels <- c("blouchOU_adapt", "blouchOU_adapt_postpc", "blouchOU_adapt_priorpc", "blouchOU_direct", "blouchOU_direct_adapt", "blouchOU_direct_adapt_postpc", "blouchOU_direct_adapt_priorpc", "blouchOU_reg", "blouchOU_reg_adapt", "blouchOU_reg_adapt_mlm_ve", "blouchOU_reg_adapt_mlm_ve_nc", "blouchOU_reg_adapt_mlm_ve_nc_postpc", "blouchOU_reg_adapt_mlm_ve_nc_priorpc", "blouchOU_reg_adapt_mlm_ve_postpc", "blouchOU_reg_adapt_mlm_ve_priorpc", "blouchOU_reg_adapt_mlm_vi", "blouchOU_reg_adapt_mlm_vi_nc", "blouchOU_reg_adapt_mlm_vi_postpc", "blouchOU_reg_adapt_mlm_vi_priorpc", "blouchOU_reg_adapt_postpc", "blouchOU_reg_adapt_priorpc", "blouchOU_reg_adapt_ve", "blouchOU_reg_adapt_ve_postpc", "blouchOU_reg_adapt_ve_priorpc", "blouchOU_reg_direct", "blouchOU_reg_direct_adapt", "blouchOU_reg_direct_adapt_mlm_ve", "blouchOU_reg_direct_adapt_mlm_ve_nc", "blouchOU_reg_direct_adapt_mlm_vi", "blouchOU_reg_direct_adapt_mlm_vi_nc", "blouchOU_reg_direct_adapt_ve", "blouchOU_reg_direct_mlm_ve", "blouchOU_reg_direct_mlm_ve_nc", "blouchOU_reg_direct_mlm_ve_nc_postpc", "blouchOU_reg_direct_mlm_ve_nc_priorpc", "blouchOU_reg_direct_mlm_ve_postpc", "blouchOU_reg_direct_mlm_ve_priorpc", "blouchOU_reg_direct_mlm_vi", "blouchOU_reg_direct_mlm_vi_nc", "blouchOU_reg_direct_mlm_vi_postpc", "blouchOU_reg_direct_mlm_vi_proiorpc", "blouchOU_reg_direct_postpc", "blouchOU_reg_direct_priorpc", "blouchOU_reg_direct_ve", "blouchOU_reg_direct_ve_postpc", "blouchOU_reg_direct_ve_priorpc", "blouchOU_reg_mlm_vi", "blouchOU_reg_mlm_vi_nc", "blouchOU_reg_postpc", "blouchOU_reg_priorpc")

# load each stan module
Rcpp::loadModule("stan_fit4blouchOU_adapt_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_adapt_postpc_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_adapt_priorpc_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_direct_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_direct_adapt_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_direct_adapt_postpc_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_direct_adapt_priorpc_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_adapt_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_adapt_mlm_ve_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_adapt_mlm_ve_nc_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_adapt_mlm_ve_nc_postpc_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_adapt_mlm_ve_nc_priorpc_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_adapt_mlm_ve_postpc_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_adapt_mlm_ve_priorpc_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_adapt_mlm_vi_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_adapt_mlm_vi_nc_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_adapt_mlm_vi_postpc_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_adapt_mlm_vi_priorpc_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_adapt_postpc_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_adapt_priorpc_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_adapt_ve_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_adapt_ve_postpc_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_adapt_ve_priorpc_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_direct_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_direct_adapt_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_direct_adapt_mlm_ve_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_direct_adapt_mlm_ve_nc_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_direct_adapt_mlm_vi_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_direct_adapt_mlm_vi_nc_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_direct_adapt_ve_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_direct_mlm_ve_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_direct_mlm_ve_nc_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_direct_mlm_ve_nc_postpc_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_direct_mlm_ve_nc_priorpc_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_direct_mlm_ve_postpc_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_direct_mlm_ve_priorpc_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_direct_mlm_vi_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_direct_mlm_vi_nc_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_direct_mlm_vi_postpc_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_direct_mlm_vi_proiorpc_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_direct_postpc_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_direct_priorpc_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_direct_ve_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_direct_ve_postpc_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_direct_ve_priorpc_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_mlm_vi_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_mlm_vi_nc_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_postpc_mod", what = TRUE)
Rcpp::loadModule("stan_fit4blouchOU_reg_priorpc_mod", what = TRUE)

# instantiate each stanmodel object
stanmodels <- sapply(stanmodels, function(model_name) {
  # create C++ code for stan model
  stan_file <- if(dir.exists("stan")) "stan" else file.path("inst", "stan")
  stan_file <- file.path(stan_file, paste0(model_name, ".stan"))
  stanfit <- rstan::stanc_builder(stan_file,
                                  allow_undefined = TRUE,
                                  obfuscate_model_name = FALSE)
  stanfit$model_cpp <- list(model_cppname = stanfit$model_name,
                            model_cppcode = stanfit$cppcode)
  # create stanmodel object
  methods::new(Class = "stanmodel",
               model_name = stanfit$model_name,
               model_code = stanfit$model_code,
               model_cpp = stanfit$model_cpp,
               mk_cppmodule = function(x) get(paste0("rstantools_model_", model_name)))
})
